INSERT INTO questions (question_type, question_name, answer_a, answer_b, answer_c, answer_d, answer, describle_answer) 
VALUES 
	(1, "Nước đá tồn tại dưới dạng nào", "Rắn", "Lỏng", "Khí", "Cả ba phương án đều sai", 1, ""), 
(1, "Gang là hợp kim của", "Sắt và Các bon", "Sắt và Silic", "Sắt và Lưu huỳnh", "Sắt và Phốtpho", 1, ""), 
(1, "Đồng thau là hợp kim của kim loại", "Sắt", "Đồng", "Nhôm", "Thiếc", 2, ""), 
(1, "Hành tinh nào sau đây không thuộc hệ mặt trời", "Thủy Tinh", "Kim Tinh", "Mộc Tinh", "Sơn Tinh", 4, ""), 
(1, "Từ nào sau đây không phải chỉ một khái niệm vật lý", "Lực hút", "Lực kéo", "Lực lưỡng", "Lực ma sát", 3, ""), 
(1, "Từ nào sau đây không để chỉ các khái niệm hóa học", "Điện tử", "Nguyên tử", "Lượng tử", "Tự tử", 4, ""), 
(1, "Quá trình chuyển đổi trạng thái từ rắn sang lỏng gọi là gì", "Nóng chảy", "Đông đặc", "Bay hơi", "Ngưng tụ", 1, ""), 
(1, "Quá trình chuyển đổi trạng thái từ khí sang lỏng gọi là gì", "Nóng Chảy", "Đông đặc", "Bay Hơi", "Ngưng tụ", 4, ""), 
(1, "Để lưu 1 tài liệu trong MS word ta dùng tổ hợp phím nào", "Ctrl S", "Ctrl A", "Ctrl D", "Ctrl L", 1, ""), 
(1, "Tổ hợp phím Ctrl N trong MS Word dùng để làm gì", "Tạo file mới", "Lưu file", "Mở file", "Đóng file", 1, ""), 
(1, "Tổ hợp phím nào dùng để mở một file trong MS Word", "Ctrl S", "Ctrl O", "Ctrl A", "Shift A", 2, ""), 
(1, "Tổ hợp phím Ctrl X trong MS Word dùng để làm gì", "Đóng", "Mở ", "Cắt", "Sao chép", 3, ""), 
(1, "Tổ hợp phím Ctrl V trong MS Word đung để làm gì ", "Đóng", "Mở", "Sao chép", "Dán", 4, ""), 
(1, "Cái nào dưới đây không phải là 1 hệ điều hành", "Windows", "Linux", "Mac OS", "Doors", 4, ""), 
(1, "Cái gì là một thiết bị máy tính", "Gà", "Mèo", "Chó", "Chuột", 4, ""), 
(1, "Đâu không phải là một sản phẩm của Apple", "iPhone", "iPad", "iPod", "iBox", 4, ""), 
(1, "Đâu không phải là một sản phẩm của Microsoft", "Windows", "Office", "Dos", "Mac", 4, ""), 
(1, "Bộ nhớ truy cập ngẫu nhiên trong máy tính được viết tắt như thế nào", "RAM", "ROM", "ROA", "RAO", 1, ""), 
(1, "1 kilogam bằng bao nhiêu gam", "1000", "10", "100", "10000", 1, ""), 
(1, "Một 1000 kilogam ứng với", "1 tấn", "1 tạ ", "1 yến", "1 kí", 1, ""), 
(1, "Một giờ có bao nhiêu phút", "15", "60", "3600", "24", 2, ""), 
(1, "Nước Việt Nam hình chữ gì", "S", "A", "L", "C", 1, ""), 
(1, "Việt Nam không tiếp giáp với quốc gia nào", "Lào ", "Campuchia", "Thái Lan", "Trung Quốc", 3, ""), 
(1, "Đỉnh núi cao nhất Việt Nam thuộc dãy núi nào", "Hoàng Liên Sơn", "Đông Triều", "Tam Đảo", "Sông Gâm", 1, ""), 
(1, "Sân bay lớn nhất phía Bắc Việt Nam", "Cát Bi", "Quảng Ninh", "Nội Bài", "Gia Lâm", 3, ""), 
(1, "Tỉnh lị của tỉnh Nghệ An ", "Vinh", "Cửa Lò", "Thái Hòa", "Đô Lương", 1, ""), 
(1, "\"Đường vô xứ Huế quanh quanh - Non xanh nước biếc như tranh ................\" gì", "sơn dầu", "sơn mài", "họa đồ", "kí họa", 3, ""), 
(1, "Núi nào nằm bên bờ sông Hương ở Huế", "núi Bạch Mã", "núi Ngự Bình", "núi Hồng Lĩnh", "núi Ba Vì", 2, ""), 
(1, "Vườn quốc gia nào sau đây không thuộc vùng Bắc Trung Bộ", "Pù Mát", "Bạch Mã", "Vũ Quang", "Ba Vì", 4, ""), 
(1, "Việt Nam nằm ở châu lục nào", "Châu Á", "Châu Mỹ", "Châu Âu", "Châu Phi", 1, ""), 
(1, "Nước nào sau đây không thuộc châu Mỹ", "Cu Ba", "Brasil", "Pháp", "Chi Lê", 3, ""), 
(1, "Nước nào sau đây thuộc châu Âu", "Việt Nam", "Mỹ", "Angola", "Thụy Sỹ", 4, ""), 
(1, "Thủ đô của nước Việt Nam là thành phố nào", "Hà Nội", "Hải Phòng", "TP Hồ Chí Minh", "Viêng Chăn", 1, ""), 
(1, "Nước có diện tích lớn nhất thế giới", "Hoa Kỳ", "Trung Quốc", "Nga", "Pháp", 3, ""), 
(1, "Trái đất có bao nhiêu đại dương", "1", "2", "3", "4", 4, ""), 
(1, "Trong các tỉnh sau đây, tỉnh nào không giáp biển", "Khánh Hòa ", "Hà Nam", "Kiên Giang", "TP Sài Gòn", 2, ""), 
(1, "Tỉnh nào sau đây thuộc khu vực Tây Nguyên", "Hà Nam", "Thái Nguyên", "Đăk Nông", "Cần Thơ", 3, ""), 
(1, "Cảng nào không thuộc vùng Đông Nam Bộ", "Cảng Sài Gòn", "Cảng Thị Vải", "Cảng Cái Mép", "Cảng Hải Phòng", 4, ""), 
(1, "Địa danh Dinh Độc Lập là thuộc thành phố nào ", "Hà Nội", "Hải Phòng", "Đà Nẵng", "TP Hồ Chí Minh", 4, ""), 
(1, "Đồng bằng sông Cửu Long là thuộc miền nào ở nước ta", "Miền Bắc", "Miền Nam", "Miền Trung", "Không thuộc miền nào cả", 2, ""), 
(1, "Việt Nam không có biên giới quốc gia với nước nào sau đây", "Lào", "Campuchia", "Trung Quốc", "Ấn Độ", 4, ""), 
(1, "Quốc gia nào sau đây không giáp biển", "Lào", "Việt Nam", "Thái Lan", "Campuchia", 1, ""), 
(1, "Hiệp hội các quốc gia Đông Nam Á viết tắt là gì", "ASEAN", "ANEAS", "AEASN", "AAESN", 1, ""), 
(1, "Thủ đô của nước Lào là thành phố nào", "Rangoon ", "Viêng Chăn", "Hà Nội", "Bangkok", 2, ""), 
(1, "\"Đi một ngày đàng, học một …..khôn\"", "thúng", "sòng", "sàng", "bát", 3, ""), 
(1, "Từ nào còn thiếu trong dấu …  \"… rách phải giữ lấy lề\"", "vở", "giấy", "sách", "bút", 2, ""), 
(1, "Từ nào còn thiếu trong dấu …  \"Chớp đông nhay nháy,… …. thì mưa\"", "chó sủa", "bò rống", "gà gáy", "mèo kêu", 3, ""), 
(1, "Từ nào còn thiếu trong dấu …  \"Hỡi cô tát nước bên đàng, sao cô múc ánh trăng … đổ đi\"", "tròn", "méo", "đỏ", "vàng", 4, ""), 
(1, "Từ nào còn thiếu trong dấu …  Ai ơi nhớ lấy câu này, cướp đêm là giặc cướp ngày là … \"", "dân", "quan", "quân", "vua", 2, ""), 
(1, "\" Gần mực thì đen, gần … thì sáng\"", "đèn", "nến", "lửa", "điện", 1, ""), 
(1, "\"… xinh … mọc đầu đình, em xinh em đứng một mình cũng xinh\" Loại cây nào còn thiếu trong dấu …", "Tre", "Dừa", "Trúc", "Cúc", 3, ""), 
(1, "Từ nào còn thiếu trong dấu …  \"Chồng người đánh bắc dẹp đông, chồng em ngồi bếp dương cung bắn…\"", "chó", "mèo", "gà", "lợn", 2, ""), 
(1, "\"Đêm tháng năm chưa nằm đã sáng, ngày tháng … chưa cười đã tối\" Tháng nào được nhắc đến trong dấu …", "Bảy", "Tám", "Chín", "Mười", 4, ""), 
(1, "Theo truyền thuyết Bánh chưng bánh dày, hoàng tử mà được vua chọn làm vua có tên là gì", "Lang Liêu", "Lang Tiêu", "Bang Liêu", "Bang Tiêu", 1, ""), 
(1, "Theo truyền thuyết, loài vật nào đã nổi lên đòi kiếm của vua Lê Lợi", "Rắn", "Cá", "Bạch tuộc", "Rùa", 4, ""), 
(1, "Trong truyện cổ tích Tấm Cám, Tấm đã không hóa thân thành cái gì ", "Quả thị", "Chim vàng anh", "Cây xoan đào", "Cây lúa", 4, ""), 
(1, "Ca sĩ nào được mệnh danh là Ông hoàng nhạc Pop (King of Pop)", "Elvis Presley", "Ronan Keating", "Micheal Jackson", "Robbie William", 3, ""), 
(1, "Thành phố nào là Thủ đô của nước Mỹ", "Washington DC", "New York", "California", "New Jersey", 1, ""), 
(1, "Đâu không phải là một yếu tố của Hiphop", "Rapping", "Beatboxing", "Graffity( Vẽ tranh đường phố)", "Trashing( Vứt rác đường phố)", 4, ""), 
(1, "Ai là tác giả bài Quốc ca của nước Việt Nam Dân Chủ Cộng Hòa", "Văn Cao", "Phạm Tuyên ", "Lưu Hữu Phước", "Đỗ Nhuận", 1, ""), 
(1, "Diễn viên Rowan Atkinson ( người vào vai Mr Bean ) là người nước nào", "Anh", "Mỹ", "Úc", "Pháp", 1, ""), 
(1, "Tìm từ khác loại với các t��� còn lại", "Tiểu thuyết", "Thơ", "Bút kí", "Bài hát", 4, ""), 
(1, "Đâu không phải là một nhân vật trong tiểu thuyết dã sử Tam Quốc Diễn Nghĩa", "Trương Phi", "Quan Vân Trường", "Tào Tháo", "Trư Bát Giới", 4, ""), 
(1, "Từ nào sau đây không dùng để chỉ một tôn giáo", "Phật giáo", "Thiên chúa giáo", "Hồi giáo", "Giàn giáo", 4, ""), 
(1, "Nơi sinh hoạt của người dân theo đạo Thiên Chúa là ở đâu", "Nhà Thờ ", "Chùa", "Đền ", "Miếu", 1, ""), 
(1, "Theo đạo Kito, Chúa Giesu đã bị tông đồ thứ mấy hãm hại", "11", "5", "7", "13", 4, ""), 
(1, "Tòa thánh Vatican là tòa thánh của tôn giáo nào", "Công giáo", "Hồi giáo", "Ấn giáo", "Phật giáo", 1, ""), 
(1, "Trạng thái nào sau đây không có trong Ngũ Hành", "Kim", "Thủy", "Thổ", "Nhựa", 4, ""), 
(1, "Ngày nào trong năm được gọi là ngày Cá tháng tư", "Ngày 1 tháng 4", "Ngày 11 tháng 4", "Ngày 20 tháng 4", "Ngày 30 tháng 4", 1, ""), 
(1, "Thủ tục nào không có trong lễ cưới của nhân dân vùng đồng bằng Bắc Bộ hiện nay", "Dạm ngõ", "Ăn hỏi", "Đám cưới", "Cướp vợ", 4, ""), 
(1, "Các liền chị khi hát quan họ Bắc Ninh thường mang loại nón nào", "Nón quai thao", "Nón bài thơ", "Nón ngựa", "Nón thúng", 1, ""), 
(1, "Đâu không phải là một nguyên liệu chính để làm món dưa muối", "Cải bẹ", "Muối", "Đường", "Khoai lang", 4, ""), 
(1, "Quân nào sau đây không có trong bộ bài Tây (tú lơ khơ)", "Q cơ", "K cơ", "J cơ", "D cơ", 4, ""), 
(1, "Đâu không phải là một triết gia nổi tiếng của Trung Quốc thời cổ", "Khổng Tử", "Mặc Tử", "Trang Tử", "Tự Tử", 4, ""), 
(1, "Thành phố nào sau đây không thuộc nước Anh", "Manchester", "London", "Liverpool", "Milan", 4, ""), 
(1, "Trang phục của các võ sĩ Karate ngày nay thường có màu gì", "Đỏ", "Đen", "Xanh lam", "Trắng", 4, ""), 
(1, "Môn võ vovinam là môn võ truyền thống của quốc gia nào", "Việt Nam", "Lào", "Campuchia", "Myanmar", 1, ""), 
(1, "Quân nào sau đây không có trên bàn cờ vua", "Xe ", "Pháo", "Mã", "Tốt", 2, ""), 
(1, "Quân Hậu là loại quân có trên bàn cờ nào", "Cờ tướng", "Cờ vua", "Cờ vây", "Cờ caro", 2, "");