INSERT INTO questions (question_type_id, question_field_id, question_name, answer_a, answer_b, answer_c, answer_d, answer, describle_answer) 
VALUES 
	(1, 1, "Nước đá tồn tại dưới dạng nào", "Rắn", "Lỏng", "Khí", "Cả ba phương án đều sai", 1, ""), 
(1, 1, "Gang là hợp kim của", "Sắt và Các bon", "Sắt và Silic", "Sắt và Lưu huỳnh", "Sắt và Phốtpho", 1, ""), 
(1, 1, "Đồng thau là hợp kim của kim loại", "Sắt", "Đồng", "Nhôm", "Thiếc", 2, ""), 
(1, 1, "Hành tinh nào sau đây không thuộc hệ mặt trời", "Thủy Tinh", "Kim Tinh", "Mộc Tinh", "Sơn Tinh", 4, ""), 
(1, 1, "Từ nào sau đây không phải chỉ một khái niệm vật lý", "Lực hút", "Lực kéo", "Lực lưỡng", "Lực ma sát", 3, ""), 
(1, 1, "Từ nào sau đây không để chỉ các khái niệm hóa học", "Điện tử", "Nguyên tử", "Lượng tử", "Tự tử", 4, ""), 
(1, 1, "Quá trình chuyển đổi trạng thái từ rắn sang lỏng gọi là gì", "Nóng chảy", "Đông đặc", "Bay hơi", "Ngưng tụ", 1, ""), 
(1, 1, "Quá trình chuyển đổi trạng thái từ khí sang lỏng gọi là gì", "Nóng Chảy", "Đông đặc", "Bay Hơi", "Ngưng tụ", 4, ""), 
(1, 1, "Để lưu 1 tài liệu trong MS word ta dùng tổ hợp phím nào", "Ctrl S", "Ctrl A", "Ctrl D", "Ctrl L", 1, ""), 
(1, 1, "Tổ hợp phím Ctrl N trong MS Word dùng để làm gì", "Tạo file mới", "Lưu file", "Mở file", "Đóng file", 1, ""), 
(1, 1, "Tổ hợp phím nào dùng để mở một file trong MS Word", "Ctrl S", "Ctrl O", "Ctrl A", "Shift A", 2, ""), 
(1, 1, "Tổ hợp phím Ctrl X trong MS Word dùng để làm gì", "Đóng", "Mở ", "Cắt", "Sao chép", 3, ""), 
(1, 1, "Tổ hợp phím Ctrl V trong MS Word đung để làm gì ", "Đóng", "Mở", "Sao chép", "Dán", 4, ""), 
(1, 1, "Cái nào dưới đây không phải là 1 hệ điều hành", "Windows", "Linux", "Mac OS", "Doors", 4, ""), 
(1, 1, "Cái gì là một thiết bị máy tính", "Gà", "Mèo", "Chó", "Chuột", 4, ""), 
(1, 1, "Đâu không phải là một sản phẩm của Apple", "iPhone", "iPad", "iPod", "iBox", 4, ""), 
(1, 1, "Đâu không phải là một sản phẩm của Microsoft", "Windows", "Office", "Dos", "Mac", 4, ""), 
(1, 1, "Bộ nhớ truy cập ngẫu nhiên trong máy tính được viết tắt như thế nào", "RAM", "ROM", "ROA", "RAO", 1, ""), 
(1, 1, "1 kilogam bằng bao nhiêu gam", "1000", "10", "100", "10000", 1, ""), 
(1, 1, "Một 1000 kilogam ứng với", "1 tấn", "1 tạ ", "1 yến", "1 kí", 1, ""), 
(1, 1, "Một giờ có bao nhiêu phút", "15", "60", "3600", "24", 2, ""), 
(1, 1, "Nước Việt Nam hình chữ gì", "S", "A", "L", "C", 1, ""), 
(1, 1, "Việt Nam không tiếp giáp với quốc gia nào", "Lào ", "Campuchia", "Thái Lan", "Trung Quốc", 3, ""), 
(1, 1, "Đỉnh núi cao nhất Việt Nam thuộc dãy núi nào", "Hoàng Liên Sơn", "Đông Triều", "Tam Đảo", "Sông Gâm", 1, ""), 
(1, 1, "Sân bay lớn nhất phía Bắc Việt Nam", "Cát Bi", "Quảng Ninh", "Nội Bài", "Gia Lâm", 3, ""), 
(1, 1, "Tỉnh lị của tỉnh Nghệ An ", "Vinh", "Cửa Lò", "Thái Hòa", "Đô Lương", 1, ""), 
(1, 1, "\"Đường vô xứ Huế quanh quanh - Non xanh nước biếc như tranh ................\" gì", "sơn dầu", "sơn mài", "họa đồ", "kí họa", 3, ""), 
(1, 1, "Núi nào nằm bên bờ sông Hương ở Huế", "núi Bạch Mã", "núi Ngự Bình", "núi Hồng Lĩnh", "núi Ba Vì", 2, ""), 
(1, 1, "Vườn quốc gia nào sau đây không thuộc vùng Bắc Trung Bộ", "Pù Mát", "Bạch Mã", "Vũ Quang", "Ba Vì", 4, ""), 
(1, 1, "Việt Nam nằm ở châu lục nào", "Châu Á", "Châu Mỹ", "Châu Âu", "Châu Phi", 1, ""), 
(1, 1, "Nước nào sau đây không thuộc châu Mỹ", "Cu Ba", "Brasil", "Pháp", "Chi Lê", 3, ""), 
(1, 1, "Nước nào sau đây thuộc châu Âu", "Việt Nam", "Mỹ", "Angola", "Thụy Sỹ", 4, ""), 
(1, 1, "Thủ đô của nước Việt Nam là thành phố nào", "Hà Nội", "Hải Phòng", "TP Hồ Chí Minh", "Viêng Chăn", 1, ""), 
(1, 1, "Nước có diện tích lớn nhất thế giới", "Hoa Kỳ", "Trung Quốc", "Nga", "Pháp", 3, ""), 
(1, 1, "Trái đất có bao nhiêu đại dương", "1", "2", "3", "4", 4, ""), 
(1, 1, "Trong các tỉnh sau đây, tỉnh nào không giáp biển", "Khánh Hòa ", "Hà Nam", "Kiên Giang", "TP Sài Gòn", 2, ""), 
(1, 1, "Tỉnh nào sau đây thuộc khu vực Tây Nguyên", "Hà Nam", "Thái Nguyên", "Đăk Nông", "Cần Thơ", 3, ""), 
(1, 1, "Cảng nào không thuộc vùng Đông Nam Bộ", "Cảng Sài Gòn", "Cảng Thị Vải", "Cảng Cái Mép", "Cảng Hải Phòng", 4, ""), 
(1, 1, "Địa danh Dinh Độc Lập là thuộc thành phố nào ", "Hà Nội", "Hải Phòng", "Đà Nẵng", "TP Hồ Chí Minh", 4, ""), 
(1, 1, "Đồng bằng sông Cửu Long là thuộc miền nào ở nước ta", "Miền Bắc", "Miền Nam", "Miền Trung", "Không thuộc miền nào cả", 2, ""), 
(1, 1, "Việt Nam không có biên giới quốc gia với nước nào sau đây", "Lào", "Campuchia", "Trung Quốc", "Ấn Độ", 4, ""), 
(1, 1, "Quốc gia nào sau đây không giáp biển", "Lào", "Việt Nam", "Thái Lan", "Campuchia", 1, ""), 
(1, 1, "Hiệp hội các quốc gia Đông Nam Á viết tắt là gì", "ASEAN", "ANEAS", "AEASN", "AAESN", 1, ""), 
(1, 1, "Thủ đô của nước Lào là thành phố nào", "Rangoon ", "Viêng Chăn", "Hà Nội", "Bangkok", 2, ""), 
(1, 1, "\"Đi một ngày đàng, học một …..khôn\"", "thúng", "sòng", "sàng", "bát", 3, ""), 
(1, 1, "Từ nào còn thiếu trong dấu …  \"… rách phải giữ lấy lề\"", "vở", "giấy", "sách", "bút", 2, ""), 
(1, 1, "Từ nào còn thiếu trong dấu …  \"Chớp đông nhay nháy,… …. thì mưa\"", "chó sủa", "bò rống", "gà gáy", "mèo kêu", 3, ""), 
(1, 1, "Từ nào còn thiếu trong dấu …  \"Hỡi cô tát nước bên đàng, sao cô múc ánh trăng … đổ đi\"", "tròn", "méo", "đỏ", "vàng", 4, ""), 
(1, 1, "Từ nào còn thiếu trong dấu …  Ai ơi nhớ lấy câu này, cướp đêm là giặc cướp ngày là … \"", "dân", "quan", "quân", "vua", 2, ""), 
(1, 1, "\" Gần mực thì đen, gần … thì sáng\"", "đèn", "nến", "lửa", "điện", 1, ""), 
(1, 1, "\"… xinh … mọc đầu đình, em xinh em đứng một mình cũng xinh\" Loại cây nào còn thiếu trong dấu …", "Tre", "Dừa", "Trúc", "Cúc", 3, ""), 
(1, 1, "Từ nào còn thiếu trong dấu …  \"Chồng người đánh bắc dẹp đông, chồng em ngồi bếp dương cung bắn…\"", "chó", "mèo", "gà", "lợn", 2, ""), 
(1, 1, "\"Đêm tháng năm chưa nằm đã sáng, ngày tháng … chưa cười đã tối\" Tháng nào được nhắc đến trong dấu …", "Bảy", "Tám", "Chín", "Mười", 4, ""), 
(1, 1, "Theo truyền thuyết Bánh chưng bánh dày, hoàng tử mà được vua chọn làm vua có tên là gì", "Lang Liêu", "Lang Tiêu", "Bang Liêu", "Bang Tiêu", 1, ""), 
(1, 1, "Theo truyền thuyết, loài vật nào đã nổi lên đòi kiếm của vua Lê Lợi", "Rắn", "Cá", "Bạch tuộc", "Rùa", 4, ""), 
(1, 1, "Trong truyện cổ tích Tấm Cám, Tấm đã không hóa thân thành cái gì ", "Quả thị", "Chim vàng anh", "Cây xoan đào", "Cây lúa", 4, ""), 
(1, 1, "Ca sĩ nào được mệnh danh là Ông hoàng nhạc Pop (King of Pop)", "Elvis Presley", "Ronan Keating", "Micheal Jackson", "Robbie William", 3, ""), 
(1, 1, "Thành phố nào là Thủ đô của nước Mỹ", "Washington DC", "New York", "California", "New Jersey", 1, ""), 
(1, 1, "Đâu không phải là một yếu tố của Hiphop", "Rapping", "Beatboxing", "Graffity( Vẽ tranh đường phố)", "Trashing( Vứt rác đường phố)", 4, ""), 
(1, 1, "Ai là tác giả bài Quốc ca của nước Việt Nam Dân Chủ Cộng Hòa", "Văn Cao", "Phạm Tuyên ", "Lưu Hữu Phước", "Đỗ Nhuận", 1, ""), 
(1, 1, "Diễn viên Rowan Atkinson ( người vào vai Mr Bean ) là người nước nào", "Anh", "Mỹ", "Úc", "Pháp", 1, ""), 
(1, 1, "Tìm từ khác loại với các t��� còn lại", "Tiểu thuyết", "Thơ", "Bút kí", "Bài hát", 4, ""), 
(1, 1, "Đâu không phải là một nhân vật trong tiểu thuyết dã sử Tam Quốc Diễn Nghĩa", "Trương Phi", "Quan Vân Trường", "Tào Tháo", "Trư Bát Giới", 4, ""), 
(1, 1, "Từ nào sau đây không dùng để chỉ một tôn giáo", "Phật giáo", "Thiên chúa giáo", "Hồi giáo", "Giàn giáo", 4, ""), 
(1, 1, "Nơi sinh hoạt của người dân theo đạo Thiên Chúa là ở đâu", "Nhà Thờ ", "Chùa", "Đền ", "Miếu", 1, ""), 
(1, 1, "Theo đạo Kito, Chúa Giesu đã bị tông đồ thứ mấy hãm hại", "11", "5", "7", "13", 4, ""), 
(1, 1, "Tòa thánh Vatican là tòa thánh của tôn giáo nào", "Công giáo", "Hồi giáo", "Ấn giáo", "Phật giáo", 1, ""), 
(1, 1, "Trạng thái nào sau đây không có trong Ngũ Hành", "Kim", "Thủy", "Thổ", "Nhựa", 4, ""), 
(1, 1, "Ngày nào trong năm được gọi là ngày Cá tháng tư", "Ngày 1 tháng 4", "Ngày 11 tháng 4", "Ngày 20 tháng 4", "Ngày 30 tháng 4", 1, ""), 
(1, 1, "Thủ tục nào không có trong lễ cưới của nhân dân vùng đồng bằng Bắc Bộ hiện nay", "Dạm ngõ", "Ăn hỏi", "Đám cưới", "Cướp vợ", 4, ""), 
(1, 1, "Các liền chị khi hát quan họ Bắc Ninh thường mang loại nón nào", "Nón quai thao", "Nón bài thơ", "Nón ngựa", "Nón thúng", 1, ""), 
(1, 1, "Đâu không phải là một nguyên liệu chính để làm món dưa muối", "Cải bẹ", "Muối", "Đường", "Khoai lang", 4, ""), 
(1, 1, "Quân nào sau đây không có trong bộ bài Tây (tú lơ khơ)", "Q cơ", "K cơ", "J cơ", "D cơ", 4, ""), 
(1, 1, "Đâu không phải là một triết gia nổi tiếng của Trung Quốc thời cổ", "Khổng Tử", "Mặc Tử", "Trang Tử", "Tự Tử", 4, ""), 
(1, 1, "Thành phố nào sau đây không thuộc nước Anh", "Manchester", "London", "Liverpool", "Milan", 4, ""), 
(1, 1, "Trang phục của các võ sĩ Karate ngày nay thường có màu gì", "Đỏ", "Đen", "Xanh lam", "Trắng", 4, ""), 
(1, 1, "Môn võ vovinam là môn võ truyền thống của quốc gia nào", "Việt Nam", "Lào", "Campuchia", "Myanmar", 1, ""), 
(1, 1, "Quân nào sau đây không có trên bàn cờ vua", "Xe ", "Pháo", "Mã", "Tốt", 2, ""), 
(1, 1, "Quân Hậu là loại quân có trên bàn cờ nào", "Cờ tướng", "Cờ vua", "Cờ vây", "Cờ caro", 2, ""), 
(1, 1, "Trong môn cờ vua, quân nào có nhiều cách di chuyển nhất", "Vua", "Hậu", "Xe", "Mã", 2, ""), 
(1, 1, "Cờ tướng là môn thể thao dành cho mấy người chơi", "Một", "Hai", "Ba", "Bốn", 2, ""), 
(1, 1, "Đại hội thể thao Olympic được tổ chức mấy năm một lần", "Hai", "Bốn", "Sáu", "Tám", 2, ""), 
(1, 1, "Sân vận động quốc gia Bắc Kinh được xây dựng phục vụ Olympic 2008 có hình gì", "Tổ chim", "Trái bom", "Quả bóng đá", "Ngọn đuốc", 1, ""), 
(1, 1, "Đại hội thể thao Đông Nam Á 2003 được tổ chức tại quốc gia nào", "Malaysia", "Indonesia", "Việt Nam", "Thái Nam", 3, ""), 
(1, 1, "Trong một trận bóng đá chuyên nghiệp, mỗi đội bóng sẽ có bao nhiêu cầu thủ chính thức", "11", "22", "9", "18", 1, ""), 
(1, 1, "Trong một trận thi đấu bóng đá, ai được chơi bóng bằng tay", "Tiền đạo", "Hậu vệ", "Trọng tài", "Thủ môn", 4, ""), 
(1, 1, "Môn thể thao nào được coi là môn thể thao vua", "Bóng đá", "Bóng rổ", "Bóng chày", "Bóng chuyền", 1, ""), 
(1, 1, "Đội tuyển quốc gia Việt Nam đã mấy lần tham dự vòng chung kết World cup", "Chưa lần nào", "1 lần", "2 lần", "3 lần", 1, ""), 
(1, 1, "Tác phẩm nào được coi là Bản tuyên ngôn độc lập đầu tiên của Việt Nam", "Nam quốc sơn hà", "Bình Ngô đại cáo", "Tuyên ngôn độc lập 1945", "Chiếu dời đô", 1, ""), 
(1, 1, "Vật nào sau đây không phải là một loại vũ khí", "Cung", "Súng", "Giáo", "Bút chì", 4, ""), 
(1, 1, "Đâu không phải là một điểm đến", "Trường học", "Vũ trường", "Sân vận động", "Giá sách", 4, ""), 
(1, 1, "Có bao nhiêu tháng trong 1 năm (dương lịch)", "12", "24", "36", "48", 1, ""), 
(1, 1, "Đâu không phải là một nhạc cụ", "Đàn ghita", "Đàn violon", "Đàn piano", "Đàn bà", 4, ""), 
(1, 1, "Ông già Noel theo tưởng tượng thường mặc bộ quần áo màu gì", "Xanh", "Đỏ", "Tím ", "Vàng", 2, ""), 
(1, 1, "Theo tưởng tượng, ông già Noel thường phát quà cho trẻ em vào đâu", "Túi quần", "Túi áo", "Mũ", "Tất", 4, ""), 
(1, 1, "Con vật nào sau đây không bay được", "Con bướm", "Con én", "Con bò", "Con ong", 3, ""),

(1, 1, "Trong danh sách sau, đâu là một ngôn ngữ lập trình", "P", "Q", "C", "D", 3, ""), 
(1, 1, "Công ty Microsoft là của công ty nào", "Mỹ", "Anh", "Đức", "Nhật", 1, ""), 
(1, 1, "Chủ tịch của công ty Microsoft", "Steve Jobs", "Bill Gates", "Paul Allen", "Tim Cook", 2, ""), 
(1, 1, "Máy tính để bàn còn được gọi là gì", "Desktop", "Laptop", "Comtop", "Chairtop", 1, ""), 
(1, 1, "đơn vị hecta tương ứng với", "1 hectomet vuông", "1 kilomet vuông", "1 decamet vuông", "1 mét vuông", 1, ""), 
(1, 1, "Đơn vị nào sau đây không phải là đơn vị chỉ diện tích", "Hecta", "Foot", "Mẫu", "Sào", 2, ""), 
(1, 1, "Bao nhiêu thước thì được 1 sào Bắc Bộ", "36", "10", "15", "360", 3, ""), 
(1, 1, "Nhà khoa học Newton người nước nào", "Anh", "Pháp", "Nga ", "Đức", 1, ""), 
(1, 1, "Ai là người phát hiện ra định luật vạn vật hấp dẫn", "Newton", "Einstein", "Gallilee", "Một người khác", 1, ""), 
(1, 1, "Đơn vị nào sau đây để chỉ năng lượng", "Watt", "kWatt giờ", "m/s", "Watt/s", 2, ""), 
(1, 1, "\"Hãy cho tôi một điểm tựa, và tôi sẽ nhấc bổng cả Trái đất.\" Câu nói này là của nhà khoa học nào", "Archimedes", "Aristoteles", "Newton", "Einstein", 1, ""), 
(1, 1, "Vi vua đầu tiên của  nhà Lê Sơ ", "Lê Lợi", "Lê Hoàn", "Lê Thánh Tông", "Lê Chiêu Thống", 1, ""), 
(1, 1, "Ai là người lãnh đạo cuộc khởi nghĩa Lam Sơn ", "Lê Thánh Tông", "Lê Lợi", "Lê Hoàn", "Hồ Quý Ly", 2, ""), 
(1, 1, "Việt Nam tiếp giáp với vịnh nào sau đây", "Vịnh Thái Lan", "Vịnh Péc xích", "Vịnh Hà Lan", "Vịnh Phần Lan", 1, ""), 
(1, 1, "Việt Nam là một quốc gia", "Nhiệt đới", "Ôn đới", "Hàn đới", "Không ở khu vực khí hậu nào cả", 1, ""), 
(1, 1, "Nhà máy thủy điện nào sau đây  nằm ở phía bắc", "NMTĐ Thác Bà", "NMTĐ Trị An", "NMTĐ Thác Mơ", "NMTĐ Đa  Nhim", 1, ""), 
(1, 1, "Thành phố nào còn được gọi là Thành phố Hoa Phượng Đỏ", "Hà Nội", "Hạ Long", "Hải Phòng", "Huế", 3, ""), 
(1, 1, "Người H'Mông ở Việt Nam tập trung chủ yếu ở vùng nào ", "Bắc Bộ", "Nam Bộ", "Bắc Trung Bộ", "Tây Nguyên", 1, ""), 
(1, 1, "Ranh giới cực bắc nước ta thuộc tỉnh nào", "Lạng Sơn", "Cao Bằng", "Bắc Cạn", "Hà Giang", 4, ""), 
(1, 1, "Sông Lam vào nước ta ở tỉnh nào", "Nghệ An", "Thanh Hóa", "Quảng Bình", "Quảng Trị", 1, ""), 
(1, 1, "Tỉnh Hà Tĩnh không giáp với tỉnh nào sau đây", "tỉnh Nghệ An", "tỉnh Quảng Bình", "Lào", "tỉnh Thanh Hóa", 4, ""), 
(1, 1, "Cầu Hàm Rồng thuộc tỉnh nào", "Thanh Hóa", "Huế", "Đà Nẵng", "Quảng Nam", 1, ""), 
(1, 1, "Thủ đô của nước Thái Lan là thành phố nào", "Băng Cốc", "Jakarta", "Bắc Kinh", "Kuala Lămpua", 1, ""), 
(1, 1, "Nước nào có thủ đô là Bắc Kinh", "Trung Quốc (Đại lục)", "Việt Nam", "Hàn Quốc", "Nhật Bản", 1, ""), 
(1, 1, "Thủ đô của CHDCND Triều Tiên", "Seul", "Bình Nhưỡng", "Tokyo", "Bắc Kinh", 2, ""), 
(1, 1, "Nước nào có dân số đông nhất thế giới (Tính đến năm 2011)", "Trung Quốc", "Ấn Độ", "Indonesia", "Hoa Kỳ", 1, ""), 
(1, 1, "Tính đến năm 2011, Ấn Độ là quốc gia có số dân cao thứ mấy trên thế giới", "Thứ nhất", "Thứ 2", "Thứ 3", "Thứ 4", 2, ""), 
(1, 1, "Chùa Cầu ở Hội An còn có tên gọi khác là gì", "Chùa Trung Quốc", "Chùa Hàn Quốc", "Chùa Triều Tiên", "Chùa Nhật Bản", 4, ""), 
(1, 1, "Ai là tác giả của bộ tranh Phố cổ Hà Nội ", "Tô Ngọc Vân", "Bùi Xuân Phái", "Diệp Minh Châu", "Nguyễn Đình Phúc", 2, ""), 
(1, 1, "Lễ khao lề thế lính để tri ân những người lính đi bảo vệ Hoàng Sa  được tổ chức hàng năm ở đâu", "Huyện đảo Lý Sơn", "Bán đảo Sơn Trà", "Phố cổ Hội An", "VinPearl land", 1, ""), 
(1, 1, "Địa danh Buôn Đôn là thuộc tỉnh nào", "Đắk Lắk", "Lâm Đồng", "Tây Ninh", "Đà Nẵng", 1, ""), 
(1, 1, "Loại đất nào là đặc trưng cho vùng Tây Nguyên", "Đất feralit", "Đất phèn", "Đất đỏ bazan", "Đất phù sa", 3, ""), 
(1, 1, "Tỉnh ven biển cực nam của tổ quốc là tỉnh nào", "Tỉnh Cà Mau", "Tỉnh Kiên Giang", "Tỉnh Sóc Trăng", "Tỉnh Bạc Liêu", 1, ""), 
(1, 1, "Quê hương \" Năm tấn \"  ở đâu", "Thái Bình", "Hưng Yên", "Trà Vinh", "An Giang", 1, ""), 
(1, 1, "Nước nào sau đây không phải là một trong những thành viên thành lập ra ASEAN", "Indonesia", "Malaysia", "Singapore", "Brunei", 4, ""), 
(1, 1, "Khối ASEAN cộng ba gồm Nhật Bản, Hàn Quốc và quốc gia nào", "Hoa Kỳ", "Trung Quốc", "Đài Loan", "CHDCND Triều Tiên", 2, ""), 
(1, 1, "Khu di tích Angkor thuộc quốc gia nào?", "Campuchia", "Lào", "Myanmar", "Thái Lan", 1, ""), 
(1, 1, "Quốc gia có số dân đông nhất Đông Nam Á", "Malaysia", "Indonesia", "Việt Nam", "Thái Lan", 2, ""), 
(1, 1, "Ngôi chùa nào được nhắc đến trong câu thơ \" Đồng Đăng có phố Kì Lừa, có nàng Tô Thị, có chùa…\"", "Tân Thanh", "Lạng Sơn", "Một Cột", "Bà Đanh", 1, ""), 
(1, 1, "\"Rủ nhau chơi khắp Long Thành, … … … phố rành rành chẳng sai\" ", "Ba mươi sáu", "Ba mươi mốt", "Ba mươi ba", "Hai mươi sáu", 1, ""), 
(1, 1, "Địa danh nào sau đây không thuộc Hà Nội", "Hồ Gươm", "Chùa Một Cột", "Văn Miếu Quốc Tử Giám", "Trường Quốc Học", 4, ""), 
(1, 1, "Đường vĩ tuyến dài nhất là", "Xích đạo", "Vòng cực", "Chí tuyến Bắc", "Chí tuyến Nam", 1, ""), 
(1, 1, "Bài hát My heart will go on là bài hát trong bộ phim nào", "Titanic", "Trân Châu Cảng", "Bố già", "Võ sĩ giác đấu", 1, ""), 
(1, 1, "Nhạc sĩ thiên tài Mozart sinh tại nơi nào", "Áo", "Thụy Sỹ", "Pháp ", "Đức", 1, ""), 
(1, 1, "Bản Sonata Ánh Trăng được viết bởi nhạc sĩ nào", "Mozart", "Beethoven", "Chopin", "Bach", 2, ""), 
(1, 1, "Liên hoan phim Cannes được tổ chức tại nước nào", "Pháp", "Tây Ban Nha", "Ý", "Đức", 1, ""), 
(1, 1, "Giải thưởng của liên hoan phim Cannes là gì", "Cành cọ vàng", "Gấu vàng", "Quả cầu vàng", "Cúp vàng", 1, ""), 
(1, 1, "Bộ phim Cuốn theo chiều gió (1939) là thuộc thể loại nào", "Chính kịch- lãng mạn", "Hành động", "Khoa học - viễn tưởng", "Hài kịch", 1, ""), 
(1, 1, "Giải thưởng của Liên hoan phim Việt Nam là gì", "Cành cọ vàng", "Bông sen vàng", "Cánh diều vàng", "Ngựa vàng", 2, ""), 
(1, 1, "Có bao nhiêu vị anh hùng Lương Sơn Bạc trong tác phẩm Thủy Hử", "100", "98", "108", "1008", 3, ""), 
(1, 1, "Tác phẩm Những người khốn khổ của đại văn hào Victor Hugo là thuộc thể loại nào", "Thơ", "Truyện ngắn", "Bút kí", "Tiểu thuyết", 4, ""), 
(1, 1, "Thể thơ Haicư  (Haiku) là loại thơ độc đáo của đất nước nào", "Nhật Bản ", "Hàn Quốc", "Trung Quốc", "Việt Nam", 1, ""), 
(1, 1, "Hai sử thi Ramayana và Mahabharata là của đất nước nào", "Ấn Độ", "Trung Quốc", "Việt Nam", "Nhật Bản", 1, ""), 
(1, 1, "Khái niệm \" Thập tự chinh\" là của tôn giáo nào", "Thiên chúa giáo", "Hồi giáo", "Phật giáo", "Ấn Độ giáo", 1, ""), 
(1, 1, "Môn võ Karate-Do là môn võ truyền thống của nước nào", "Nhật Bản", "Ấn Độ", "Việt Nam", "Hàn Quốc", 1, ""), 
(1, 1, "Trong môn cờ tướng, quân nào khi sang sông sẽ có thêm một cách đi nữa", "Tướng", "Tượng", "Xe", "Tốt", 4, ""), 
(1, 1, "Futsal là một loại hình trong nhà của môn thể thao nào", "Bóng đá", "Bóng chày", "Tennis", "Bơi", 1, ""), 
(1, 1, "Môn thể thao cầu mây có nguồn gốc xuất xứ từ khu vực nào ở châu Á", "Đông Nam Á", "Đông Á", "Tây Nam Á", "Trung Á", 1, ""), 
(1, 1, "Đại hội thể thao Olympic hiện đại đầu tiên được tổ chức tại quốc gia nào", "Hy Lạp", "Pháp", "Mỹ", "Trung Quốc", 1, ""), 
(1, 1, "Trên lá cờ của Olympic có mấy vòng tròn", "5", "4", "3", "2", 1, ""), 
(1, 1, "Nước nào ở châu Phi lần đầu tiên đăng cai giải vô địch bóng đá thế giới", "Nam Phi", "Ai Cập", "Libi", "Nigeria", 1, ""), 
(1, 1, "FIFA là tên viết tắt của liên đoàn bóng đá nào sau đây", "LĐBĐ Thế giới", "LĐBĐ Việt Nam", "LĐBĐ Châu Âu", "LĐBĐ Đông Nam Á", 1, ""), 
(1, 1, "Có bao nhiêu đội bóng tham dự một kỳ World cup ( tính đến ngày nay )", "16", "32", "64", "48", 2, ""), 
(1, 1, "Biểu tượng của giải bóng đá ngoại hạng Anh Premier League là con vật nào", "Mèo", "Sư tử", "Gà", "Trâu", 2, ""), 
(1, 1, "Quốc hiệu Việt Nam về đời Hồng Bàng là", "Văn Lang", "Âu Lạc", "Đại Việt", "An Nam", 1, ""), 
(1, 1, "Quốc hiệu Việt Nam dưới thời Thục An Dương Vương là gì", "An Nam", "Đại Việt", "Âu Lạc", "Văn Lang", 3, ""), 
(1, 1, "Tại sao ta lại dùng tên nước là Việt Nam chứ không phải là An Nam như ngày xưa", "Vì Việt Nam dài hơn", "Vì để có dấu ấn khác ngày xưa", "Vì An Nam đọc không hay", "Vì An Nam có ngụ ý thần phục nước Tàu", 4, ""), 
(1, 1, "Vị anh hùng nào được nhân dân suy tôn là Bố Cái Đại Vương", "Phùng Hưng", "Ngô Quyền", "Mai Hắc Đế", "Đinh Bộ Lĩnh", 1, ""), 
(1, 1, "Quê hương của Phùng Hưng nay thuộc làng nào thuộc Hà Tây (cũ)", "Đường Lâm", "Cổ Đông", "Kim Sơn", "Thanh Mỹ", 1, ""), 
(1, 1, "Đường Lâm là đất hai vua, đó là Phùng Hưng và vua nào", "Ngô Quyền", "Đinh Bộ Lĩnh", "Lê Hoàn", "Lê Lợi", 1, ""), 
(1, 1, "Bí quyết thắng trận trong chiến thắng Bạch Đằng đánh đuổi quân Nam Hán là nhờ đâu", "Thủy triều và bãi cọc", "Thuyền lớn", "Pháo binh", "Đông quân", 1, ""), 
(1, 1, "Triều đại nào chấm dứt chế độ đô hộ phương bắc, mở đầu cho thời kỳ độc lập tự chủ của nước ta", "Ngô", "Đinh", "Lý ", "Trần", 1, ""), 
(1, 1, "Đinh Bộ Lĩnh lên ngôi hoàng đế đã đóng đô ở đâu", "Thăng Long", "Hoa Lư", "Huế", "Nam Định", 2, ""), 
(1, 1, "Triều đại nào sau đây là triều đại kế sau nhà Đinh", "Tiền Lê", "Hậu Lê", "Lý", "Trần", 1, ""), 
(1, 1, "Sự kiện dời đô từ Hoa Lư ra thành Đại La diễn ra vào thời nào", "Tiền Lê", "Lý ", "Trần", "Hồ", 2, ""), 
(1, 1, "Văn Miếu ở Thăng Long được lập ra với mục đích để thờ ai", "Lý Thái Tổ", "Khổng Tử", "Mạnh Tử", "Tôn Tử", 2, ""), 
(1, 1, "Điền từ còn thiếu vào câu thơ đầu tiên của bài Nam quốc sơn hà \"Nam quốc sơn hà nam ... cư\"", "Vương", "Đế", "Vua", "Dân", 2, ""), 
(1, 1, "Nguyên tố hóa học nào có kí hiệu là F", "Sắt", "Đồng", "Nhôm", "Chì", 1, ""), 
(1, 1, "Kí hiệu hóa học của nguyên tố Ch", "Fe", "Cu", "Pb", "Al", 3, ""), 
(1, 1, "Nguyên tố hóa học có nguyên tử khối nhỏ nhấ", "Hidro", "Heli", "Liti", "Natri", 1, ""), 
(1, 1, "Chất nào sau đây không phải là kim loạ", "Natri", "Sắt", "Đồng", "Phôtpho", 4, ""), 
(1, 1, "Chất nào sau đây không tồn tạ", "O2", "O3", "O4", "H2O2", 3, ""), 
(1, 1, "Kim loại nào dưới đây ở thể lỏn", "Hg", "Al", "Fe", "Mg", 1, ""), 
(1, 1, "Trọng lực trên trái đất gấp khoảng mấy lần trọng lực trên mặt trăn", "4", "5", "6", "bằng nhau", 3, ""), 
(1, 1, "Chất nào sau đây không phải là chất vô c", "Sắt", "Đồng", "Nhôm", "Rượu Etylic", 4, ""), 
(1, 1, "Ai là ông chủ của hãng Microsof", "Bill Gates", "Steve Jobs", "Elton John", "Đáp án khác", 1, ""), 
(1, 1, "Từ nào sau đây không dùng để chỉ một tôn giáo thờ chúa Giesu", "Cơ Đốc giáo", "Kito giáo", "Đạo tin lành", "Ấn Độ giáo", 4, ""), 
(1, 1, "Theo kinh thánh, đấng sáng tạo ra vũ trụ là ai", "Thiên Chúa", "Chúa Giesu", "Đức mẹ Maria", "Ngọc hoàng", 1, ""), 
(1, 1, "Đạo Islam là tên gọi khác của đạo nào", "Đạo Hồi", "Đạo Phật", "Đạo Tin Lành", "Ấn Độ giáo", 1, ""), 
(1, 1, "Quốc giáo của Thái Lan là tôn giáo nào", "Phật giáo", "Kito giáo", "Đạo Tin Lành", "Hồi giáo", 1, ""), 
(1, 1, "Nước nào sau đây không thuộc nhóm các quốc gia công nghiệp hàng đầu thế giới G8", "Anh", "Ý", "Canada", "Brazil", 4, ""), 
(1, 1, "Origami là nghệ thuật gấp giấy của nước nào", "Nhật Bản", "Hàn Quốc", "Trung Quốc", "Ấn Độ", 1, ""), 
(1, 1, "Theo thần thoại Hy Lạp, Heracles là con riêng của vị thần nào", "Zeus", "Apollo", "Poseidon", "Hades", 1, ""), 
(1, 1, "Bức tranh Nàng Mona Lisa là của họa sĩ nào", "Leonardo da Vinci", "Michelangelo", "van Gogh", "Levitan", 1, ""), 
(1, 1, "Hàng nào sau đây không có trong bài tổ tôm", "Vạn", "Văn", "Sách", "Nhất", 4, ""), 
(1, 1, "Triều đại phong kiến cuối cùng của Trung Quốc", "Thanh", "Minh", "Nguyên", "Tống", 1, ""), 
(1, 1, "Chủ nghĩa tam dân của Tôn Trung Sơn không có điều nào sau đây", "Dân tộc độc lập", "Dân chủ tự do", "Dân sinh hạnh phúc", "Dân sinh hòa bình", 4, ""), 
(1, 1, "Cây đàn Ghita ngày nay có xuất xứ từ nước nào", "Tây Ban Nha", "Anh", "Pháp", "Nga", 1, ""), 
(1, 1, "Đội tuyển bóng đá nào sau đây không phải của Tây Ban Nha", "Real Madrid", "Barcelona", "Valencia", "Chelsea", 4, ""), 
(1, 1, "Quốc gia nào có tên nghĩa là vùng đất trũng ", "Hà Lan ( Nederlanden )", "Ba Lan ( Poland )", "Ý ( Italia )", "Pháp ( France )", 1, ""), 
(1, 1, "Đất nước nào được mệnh danh là xứ sở bò tót ", "Anh", "Tây Ban Nha", "Mỹ", "Philipine", 2, ""), 
(1, 1, "Đất nước nào được mệnh danh là sứ xở hoa Tulip ", "Hà Lan", "Phần Lan", "Thái Lan", "Ba Lan", 1, ""), 
(1, 1, "Nước Việt Nam thuộc vào múi giờ nào so với giờ GMT", "+7", "+8", "+9", "+10", 1, ""), 
(1, 1, "Tháo Eiffel được coi là biểu tượng của nước nào", "Pháp", "Ấn Độ", "Nga", "Trung Quốc", 1, ""), 
(1, 1, "Vùng nào sau đây không thuộc Vương quốc Liên hiệp Anh và Bắc Ireland (UK) ", "Anh ( England )", "Wales", "Scotland", "Guam", 4, ""), 
(1, 1, "Tên viết tắt của đồng bảng Anh ", "GBP", "USD", "VND", "EUR", 1, ""), 
(1, 1, "Môn võ Aikido là môn võ thuật hiện đại của quốc gia nào", "Nhật Bản", "Hàn Quốc", "Trung Quốc", "Thái Lan", 1, ""), 
(1, 1, "Triều đại phong kiến nào tiếp nối triều đại nhà Lý", "Đinh", "Trần", "Hồ", "Nguyễn", 2, ""), 
(1, 1, "Thị xã Cẩm Phả là thuộc tỉnh nào của nước ta", "Quảng Ninh", "Thái Bình", "Thanh Hóa", "Nghệ An", 1, ""), 
(1, 1, "Nhà phát minh vĩ đại Thomas Edison là người nước nào", "Anh", "Pháp", "Nga", "Mỹ", 4, ""), 
(1, 1, "Công ty nào sau đây là của nước Mỹ", "Samsung", "Toyota", "Nokia", "Microsoft", 4, ""), 
(1, 1, "Trong đêm Noel, ông già Noel cưỡi con gì để đi phát quà", "Tuần lộc", "Ngựa ", "Chó", "Kì Lân", 1, ""), 
(1, 1, "Đâu là một nhận xét đúng khi nói về địa lý của nước Nga", "Bắc bán cầu", "Cận xích đạo", "Nam bán cầu", "Nhiệt đới", 1, ""), 
(1, 1, "Màu áo truyền thống của đội tuyển quốc gia Hà Lan là màu gì", "Xanh lam", "Trắng", "Da cam", "Đỏ", 3, ""),
(1, 1, "Lê Lợi sinh ra ở thế kỷ nào ", "Thế kỷ 13", "Thế kỷ 14", "Thế kỷ 15", "Thế kỷ 16", 2, ""), 
(1, 1, "Vùng đồng bằng sông Hồng có hình gì", "Tam giác", "Tứ giác", "Nan quạt", "Con mèo", 1, ""), 
(1, 1, "Dòng sông nào còn được gọi là sông Đen", "Sông Hồng", "Sông Đà", "Sông Lam", "Sông Mã", 2, ""), 
(1, 1, "Tỉnh nào sau đây không thuộc đồng bằng sông Hồng", "Vĩnh Phúc", "Bắc Ninh", "Thái Bình", "Thái Nguyên", 4, ""), 
(1, 1, "Thành phố Hải Phòng không giáp với tỉnh nào đây", "Thái Bình ", "Quảng Ninh", "Hải Dương", "Bắc Ninh", 4, ""), 
(1, 1, "Cao nguyên Mộc Châu thuộc tỉnh nào", "Sơn La", "Lai Châu ", "Điện Biên", "Cao Bằng", 1, ""), 
(1, 1, "Quặng Apatit ở Việt Nam chủ yếu tập trung ở tỉnh nào", "Lào Cai", "Cao Bằng", "Bắc Cạn", "Sơn La", 1, ""), 
(1, 1, "Hồ Ba bể thuộc tỉnh nào dưới đây", "Bắc Kạn", "Thái Nguyên", "Hưng Yên", "Hải Dương", 1, ""), 
(1, 1, "Quần Đảo Cô Tô thuộc tỉnh nào của Việt Nam", "Quảng Ninh", "Hải Phòng", "Hải Dương", "Thái Bình", 1, ""), 
(1, 1, "Tỉnh nào sau đây không giáp Lào", "Lào Cai", "Lai Châu ", "Sơn La", "Thanh Hóa", 1, ""), 
(1, 1, "Tỉnh nào sau đây không thuộc vùng Bắc Trung Bộ của Việt Nam", "Thừa Thiên Huế", "Quảng Bình", "Quảng Trị", "Quảng Ngãi", 4, ""), 
(1, 1, "Núi gì cùng với sông Lam được xem là biểu tượng của xứ Nghệ", "Núi Bài Thơ", "Núi Hồng Lĩnh", "Núi Cửa Lò", "Núi Nhật Lệ", 2, ""), 
(1, 1, "Thành phố Đồng Hới là tỉnh lị của tỉnh nào ", "Quảng Trị", "Quảng Nam", "Quảng Ngãi", "Quảng Bình", 4, ""), 
(1, 1, "Vườn Quốc Gia Phong Nha Kẻ Bàng, di sản văn hóa thế giới thuộc tỉnh nào của Việt Nam", "Quảng Nam", "Đà Nẵng", "Quảng Trị", "Quảng Bình", 4, ""), 
(1, 1, "Dòng sông nào thuộc tỉnh Quảng Bình đã từng chứng kiến sự chia cắt đất nước", "sông Nhật Lệ", "sông Gianh", "sông Bến Hải", "sông Hương", 2, ""), 
(1, 1, "Địa danh lịch sử Ngã Ba Đồng Lộc thuộc tỉnh nào", "Nghệ An", "Hà Tĩnh", "Thanh Hóa", "Quảng Bình", 2, ""), 
(1, 1, "Vương Quốc Gia Bạch Mã nằm ở tỉnh nào", "Quảng Nam", "Đà Nẵng", "Thừa Thiên - Huế", "Quảng Trị", 3, ""), 
(1, 1, "Thành phố Đông Hà là tỉnh lỵ của tỉnh nào", "Quảng Nam", "Quảng Bình", "Quảng Trị", "Quảng Ngãi", 3, ""), 
(1, 1, "Sông Bến Hải, nơi chia cắt đất nước ta làm hai miền nam bắc thuộc tỉnh nào", "Quảng Bình", "Quảng Trị", "Quảng Nam", "Huế", 2, ""), 
(1, 1, "Nước có diện tích lớn thứ hai trên thế giới", "Nga", "Mỹ", "Úc", "Canada", 4, ""), 
(1, 1, "Thành phố nào được mệnh danh là kinh đô ánh sáng của châu Âu", "Milan", "Paris", "London", "New York", 2, ""), 
(1, 1, "Huyện đảo Hoàng Sa thuộc tỉnh thành nào của VIệt Nam", "Đà Nẵng", "Bà Rịa - Vũng Tàu", "Bình Thuận", "Huế", 1, ""), 
(1, 1, "Thành phố nào sau đây không phải là thành phố trực thuộc Trung Ương", "Hải Phòng", "Đà Nẵng", "Cần Thơ", "Huế", 4, ""), 
(1, 1, "Tỉnh nào duy nhất của Việt Nam có 2 di sản văn hóa vật thể thế giới được UNESCO công nhận", "Quảng Ninh", "Hà Nội", "Quảng Nam", "Huế", 3, ""), 
(1, 1, "Huyện đảo tiền tiêu - Lý Sơn nằm ở tỉnh nào", "Quảng Ngãi", "Đà Nẵng", "Khánh Hòa", "Kontum", 1, ""), 
(1, 1, "Xe tăng là vũ khí ra đời trong cuộc chiến tranh nào", "Thế chiến I", "Chiến tranh Pháp - Phổ", "Thế chiến II", "Chiến tranh Việt Nam", 1, ""), 
(1, 1, "Nước nào sau đây không sử dụng đơn vị tiền tệ là euro (EUR )", "Tây Ban Nha", "Anh", "Áo", "Hy Lạp", 2, ""), 
(1, 1, "Tiểu thuyết Đôn Kihôtê được viết bởi nhà văn người nước nào", "Tây Ban Nha", "Bồ Đào Nha", "Pháp", "Anh", 1, ""), 
(1, 1, "Nhân vật nào sau đây không có trong tiểu thuyết Đông Ki Sốt (Don Quixote ) của Cesvantes ", "Hiệp sĩ Đôn Kihôtê", "Công nương Đuyn-xi-nê-a (Dulcinea)", "Giám mã Xan-chô Pan-xa (Sancho Panza ) ", "Bá tước de Moocxep", 4, ""), 
(1, 1, "Nước nào sau đây không phải là một thành viên thường trực của hội đồng bảo an LHQ (tính đến năm 2012 )", "Pháp", "Anh", "Nga", "Ấn Độ", 4, ""), 
(1, 1, "Sông nào sau đây chảy qua thủ đô London của nước Anh", "Sông Thêm ( Thames)", "Sông Vonga", "Sông Seine", "Sông Nin", 1, ""), 
(1, 1, "Lưỡng Hà là từ để chỉ hai vùng châ thổ thuộc sông Euphrates và sông nào ", "Tigris", "Dương Tử", "Sông Hằng", "Sông Colorado", 1, ""), 
(1, 1, "Vị tổng thống đầu tiên của nước Mỹ", "George Washington", "John Adams", "Thomas Jefferson", "James Madison", 1, ""), 
(1, 1, "Tổng thống nào người Mỹ đã tuyên ngôn giải phóng chế độ nô lệ tại Mỹ", "Lincoln", "Franklin Roosevelt", "George Washington", "John Kennedy", 1, ""), 
(1, 1, "Ai là thủ tướng Anh trong thời thế chiến thứ hai", "Churchill", "Clement Attlee", "Tony Blair", "Thatcher", 1, ""), 
(1, 1, "Robert McNamara đã làm chức vụ gì trong thời Chiến tranh Việt Nam", "Bộ trưởng bộ ngoại giao Hoa Kỳ", "Bộ trưởng bộ quốc phòng Hoa Kỳ", "Tổng thống Hoa Kỳ", "Đại sứ Hoa Kỳ tại nam Việt Nam", 2, ""), 
(1, 1, "Vận động viên quyền anh huyền thoại Muhammad Ali là người nước nào?", "Anh", "Pháp", "Mỹ", "Canada", 3, ""), 
(1, 1, "Quân cờ ra đời muộn nhất của môn Cờ tướng là quân nào", "Xe", "Pháo", "Mã", "Tốt", 2, ""), 
(1, 1, "Hai câu thơ \" Lạc nước hai xe đành bỏ phí - Gặp thời một tốt cũng thành công\" là của tác giả nào", "Phan Bội Châu", "Phan Châu Trinh", "Hồ Chí Minh", "Võ Nguyên Giáp", 3, ""), 
(1, 1, "Khi được Hoa Đà chữa vết thương ở tay, Quan Vũ vẫn thản nhiên chơi cờ. Đó là loại cờ nào", "Cờ tướng", "Cờ cá ngựa", "Cờ vây", "Cờ Caro", 3, ""), 
(1, 1, "Vận động viên Michael Phelps là người đã phá kỷ lục về số HCV Olympics ở bộ môn nào", "Điền kinh", "Bơi lội", "Đua thuyền", "Bắn súng", 2, ""), 
(1, 1, "Vận động viên bơi lội Michael Phelps, người đã đoạt 18 HCV Olympics là người nước nào", "Mỹ", "Anh", "Canada", "Úc", 1, ""), 
(1, 1, "Màu nào sau đây không có trên Lá cờ Olympic", "Đen", "Đỏ", "Xanh lam", "Tím", 4, ""), 
(1, 1, "Thành phố nào đã đăng cai thế vận hội 2004", "Athens", "London", "Sydney", "Bắc Kinh", 1, ""), 
(1, 1, "Thành phố sẽ tổ chức Thế vận hội vào năm 2018", "Lyon", "St Petersburg", "Seul", "Rio de Janeiro", 4, ""), 
(1, 1, "Năm nào sau đây không được tổ chức thế vận hội mùa hè", "1896", "2008", "1944", "1976", 3, ""), 
(1, 1, "Vị HLV nào là người dẫn dắt đội tuyển Đức vô địch World Cup 1990", "Franz Beckenbauer", "Rudi Voller", "Jürgen Klinsmann", "Joachim Löw", 1, ""), 
(1, 1, "Hòn đảo du lịch Bali là thuộc quốc gia nào ở châu Á", "Indonesia", "Malaysia", "Singapore", "Thái Lan", 1, ""), 
(1, 1, "Tôn giáo có nhiều tín đồ nhất trên thế giới", "Kito giáo", "Hồi giáo", "Ấn Độ giáo", "Phật giáo", 1, ""), 
(1, 1, "Ai được coi là khai tổ của Đạo giáo", "Lão Tử", "Khổng Tử", "Mạnh tử", "Mặc Tử", 1, ""), 
(1, 1, "Khái niệm nào sau đây là đúng so với Ngũ hành tương sinh tương khắc", "Kim sinh Mộc", "Mộc sinh Thủy", "Thủy sinh Kim", "Kim sinh Thủy", 4, ""), 
(1, 1, "Nước nào ở khu vực Trung Đông còn được gọi là Persia", "Iran", "Lebanon", "Syria", "Kuwait", 1, ""), 
(1, 1, "Làng Đông Hồ, nổi tiếng với tranh dân gian Đông Hồ thuộc tỉnh nào", "Bắc Ninh", "Bắc Giang", "Ninh Bình", "Hà Tây", 1, ""), 
(1, 1, "Loại giấy được dùng để in tranh dân gian Đông Hồ", "Giấy than", "Giấy tráng", "Giấy dó", "Giấy can", 3, ""), 
(1, 1, "Quốc gia nào sau đây là thành viên của cộng đồng Pháp ngữ", "Việt Nam", "Thái Lan", "Malaysia", "Indonesia", 1, ""), 
(1, 1, "Khối thịnh vượng chung là tổ chức các quốc gia độc lập từng là thuộc địa của đế quốc nào", "Anh", "Pháp", "Đức", "Mỹ", 1, ""), 
(1, 1, "Trụ sở của tổ chức Liên Hợp Quốc (United Nations ) được đặt tại quốc gia nào", "Mỹ", "Anh", "Bỉ", "Thụy Sỹ", 1, ""), 
(1, 1, "Chương trình phát triển Liên Hợp Quốc viết tắt là gì", "UNIP", "UNDP", "UNCP", "UNPP", 2, ""), 
(1, 1, "Trương Tử Lâm, hoa hậu thế giới 2007, là người nước nào", "Đài Loan", "Trung Quốc đại lục", "Singapore ", "Hàn Quốc", 2, ""), 
(1, 1, "Kênh đào Suez thuộc chủ quyền quốc gia nào", "Ai Cập", "Anh ", "Pháp", "Mỹ", 1, ""), 
(1, 1, "Kênh đào Panama là kênh đào nối hai đại dương nào", "Thái Bình Dương và Đại Tây Dương", "Thái Bình Dương và Ấn Độ Dương", "Đại Tây Dương và Ấn Độ Dương", "Đại Tây Dương và Bắc Băng Dương", 1, ""), 
(1, 1, "Công trình nổi tiếng Vạn Lý Trường Thành được khởi đầu từ triều đại nào của Trung Quốc", "Tần", "Hán", "Tống", "Minh", 1, ""), 
(1, 1, "Ai là vị vua đầu tiên của nhà Hán ( Trung Quốc )", "Lưu Bang", "Hán Vũ Đế", "Hán Văn Đế", "Hán Chiêu Đế", 1, ""), 
(1, 1, "Võ Tắc Thiên, nữ hoàng duy nhất trong lịch sử Trung Quốc sống trong thời nào", "Hán", "Đường", "Tống", "Thanh", 2, ""), 
(1, 1, "Thủ đô của triều Tống ở Trung Quốc là ở đâu", "Trường An", "Bắc Kinh", "Khai Phong", "Hàng Châu", 3, ""), 
(1, 1, "Cuộc chiến tranh thuốc phiện ( nha phiến ) lần thứ nhất tại Trung Quốc xảy ra giữa quân đội nhà Thanh với nước nào", "Anh", "Tây Ban Nha", "Pháp", "Mỹ", 1, ""), 
(1, 1, "Sau cuộc chiến tranh thuốc phiện ( nha phiến ) lần thứ nhất, Trung Quốc phải nhượng lại vùng đất nào cho Anh", "Hồng Kông", "Macau", "Đài Loan", "Hải Nam", 1, ""), 
(1, 1, "Chiến trường chính của chiến tranh thế giới lần một là ở châu lục nào", "Châu Á", "Châu Âu", "Châu Mỹ", "Châu Phi", 2, ""), 
(1, 1, "Nước nào sau đây không cùng một phe với các nước còn lại trong Thế Chiến I ", "Đức", "Áo - Hung", "Bulgaria", "Anh", 4, ""), 
(1, 1, "Nước nào đã rút ra khỏi cuộc chiến tranh thế giới lần thứ nhất sau khi kí kết hòa ước với Đức", "Anh", "Nga", "Pháp", "Ý", 2, ""), 
(1, 1, "Giải vô địch bóng đá thế giới World cup lần đầu tiên được tổ chức tại quốc gia nào", "Uruguay", "Paraguay", "Brasil", "Đức", 1, ""), 
(1, 1, "Giải vô địch bóng đá thế giới được tổ chức vào năm 1930 là giải vô địch thứ bao nhiêu", "Thứ nhất", "Thứ hai", "Thứ ba", "Thứ tư", 1, ""), 
(1, 1, "Tính đến năm 2012, quốc gia nào dẫn đầu về thành tích vô địch World cup", "Đức", "Argentina", "Italia", "Brasil", 4, ""), 
(1, 1, "Đổi tuyển quốc gia Đức đã giành được bao nhiêu chức vô địch World Cup", "2", "3", "4", "5", 2, ""), 
(1, 1, "Đội tuyển nào đã vô địch giải vô địch bóng đá thế giới tổ chức tại Nam Phi 2010", "Tây Ban Nha", "Hà Lan", "Uruguay", "Pháp", 1, ""), 
(1, 1, "Diego Maradona đã dẫn dắt đội tuyển bóng đá quốc gia Argentina tại kỳ World cup nào", "1998", "2002", "2006", "2010", 4, ""), 
(1, 1, "Liên đoàn bóng đá chât Á được viết tắt như thế nào", "UEFA", "CAF", "CONMEBOL", "AFC", 4, ""), 
(1, 1, "Đội tuyển vô địch giải vô địch bóng đá châu Âu 2008 tại Áo và Thụy Sỹ", "Tây Ban Nha", "Đức", "Pháp", "Nga", 1, ""), 
(1, 1, "Đội bóng nước Anh nào sau đây giành được nhiều cúp C1 Châu Âu nhất so với các đội còn lại", "Manchester United", "Liverpool", "Arsenal", "Aston Villa", 2, ""), 
(1, 1, "Đội bóng nào có tổng số lần vô địch giải ngoại hạng Anh nhiều nhất", "Manchester United", "Liverpool", "Arsenal", "Chelsea", 1, ""), 
(1, 1, "SVĐ Anfield là sân nhà của đội bóng nào", "Everton", "Liverpool", "Arsenal", "Chelsea", 2, ""), 
(1, 1, "\"Những con quỷ đỏ\" - Red Devils là biệt danh của đội bóng nào dưới đây?", "Manchester United", "Arsenal", "AC Milan", "Barcelona", 1, ""), 
(1, 1, "Sân nhà của đội bóng Manchester United", "Old Trafford", "Stamford Bridge", "City of Manchester", "highbury", 1, ""), 
(1, 1, "Màu áo chính thức của CLB Manchester City là màu nào", "Đỏ", "Xanh Da Trời", "Đen", "Vàng", 2, ""), 
(1, 1, "Câu lạc bộ bóng đá nào sau đây không đến từ thành London ", "Chelsea", "Arsenal", "Everton", "Fulham", 3, ""), 
(1, 1, "Triều đại nào ở Trung Quốc khi còn cai trị nước ta đã đặt nước ta là An Nam Đô Hộ Phủ", "Hán ", "Đường", "Tống ", "Nguyên", 2, ""), 
(1, 1, "Vua nào đã đổi tên nước ta thành Đại Cồ Việt", "Đinh Bộ Lĩnh", "Lý Công Uẩn", "Ngô Quyền", "Quang Trung", 1, ""), 
(1, 1, "Ngô Quyền đã đánh thắng giặc Nam Hán trên sông Bạch Đằng vào năm nào", "938", "948", "958", "968", 1, ""), 
(1, 1, "Giai đoạn loạn 12 sứ quân là giai đoạn sau triều đại phong kiến nào", "Ngô", "Đinh", "Tiền Lê", "Lý", 1, ""), 
(1, 1, "Cố đô Hoa Lư thời Đinh Tiên Hoàng nay thuộc tỉnh nào của nước ta", "Hà Nội", "Ninh Bình", "Thái Bình", "Nghệ An", 2, ""), 
(1, 1, "Vua Ngọa Triều là vua của triều đại phong kiến nào ở Việt Nam", "Ngô", "Hậu Lê", "Tiền Lê", "Trần", 3, ""), 
(1, 1, "Nguyên nhân chính của việc Lê Hoàn được các đại thần và Thái hậu nhà Đinh tôn lên làm vua", "Do việc nước quá vất vả", "Do quân Chiêm Thành xâm lược", "Do quân Tông xâm lược", "Do dân không theo nhà Đinh nữa", 3, ""), 
(1, 1, "Lý Thái Tổ lên ngôi hoàng đế năm nào", "1000", "1008", "1009", "1010", 3, ""), 
(1, 1, "Lý Công Uẩn sinh tại Cổ Pháp tính đến nay là thuộc tỉnh nào", "Bắc Ninh", "Ninh Bình", "Hà Nội", "Hưng Yên", 1, ""), 
(1, 1, "Kim loai nào dẫn điện tốt nhấ", "Bạc", "Đồng", "Nhôm", "Vàng", 1, ""), 
(1, 1, "Một ion có điện tích dương được gọi là g", "Cation", "Anion", "Barion", "Halidon", 1, ""), 
(1, 1, "Nước đá khô có công thức là g", "H20", "C02", "H2O2", "O3", 2, ""), 
(1, 1, "Kim loại có nhiệt độ nóng chảy cao nhấ", "Nhôm", "Sắt", "Crom", "Vonfram", 4, ""), 
(1, 1, "Nguyên tố chiếm tỉ lệ nhiều nhất trong vũ tr", "Oxy", "Hidro", "Heli", "Các bon", 2, ""), 
(1, 1, "Trong phản ứng hóa học, đồng không phản ứng với chất nào dưới đâ", "Axit Sunfuric", "Axit Clohidric", "Axit Nitric", "Sắt 3+", 2, ""), 
(1, 1, "Đồng có bao nhiêu đồng vị ổn địn", "1", "2", "3", "4", 2, ""), 
(1, 1, "Nguyên tố nào là duy nhất có những tên khác nhau cho những đồng vị khác nha", "Hidro", "Cesi", "Liti", "Không có nguyên tố như vậy", 1, ""), 
(1, 1, "Một KiloByte tương ứng với bao nhiêu byt", "1024", "512", "128", "64", 1, ""), 
(1, 1, "Một byte gồ", "8 bit", "16 bit", "32 bit", "1024 bit", 1, ""), 
(1, 1, "Một GigaByte tương đương với bao nhiêu byt", "10 mũ 3", "10 mũ 6", "10 mũ 9", "10 mũ 12", 3, ""), 
(1, 1, "Tên viết tắt của mạng cục b", "WAN", "GAN", "LAN", "SAN", 3, ""), 
(1, 1, "Đâu không phải là một dịch vụ của hãng Googl", "Gmail", "Google Maps", "AdWords", "Push", 4, ""), 
(1, 1, "Tên niêm yết trên thị trường chứng khoán NASDAG của công ty Googl", "GOOG", "GOGL", "GOGE", "GOLE", 1, ""), 
(1, 1, "Chữ W thứ 2 trong WWW là viết tắt của từ nào trong tiếng An", "World", "Wide", "Web", "Wild", 2, ""), 
(1, 1, "Internet chính thức xuất hiện ở Việt Nam vào năm bao nhiê", "1995", "1997", "1999", "2000", 2, ""), 
(1, 1, "Tiền thân của mạng Internet ngày na", "ARPANET", "ULTANET", "WANNET", "WATNET", 1, ""), 
(1, 1, "Số 10 hệ thập phân được biểu diễn trong hệ nhị phân như thế nà", "1010", "1100", "1001", "0110", 1, ""), 
(1, 1, "Số 0011 trong hệ nhị phân biểu diễn số nào trong hệ thập phâ", "2", "3", "4", "5", 2, ""), 
(1, 1, "1 sào bắc bộ bằn", "100 m2", "1000 m2", "360 m2", "3600 m2", 3, ""), 
(1, 1, "Một mẫu bằng bao nhiêu sà", "10", "36", "100", "360", 1, ""), 
(1, 1, "Nhà khoa học Galileo Galilei là người nước nà", "Italia", "Pháp", "Tây Ban Nha ", "Bồ Đào Nha", 1, ""), 
(1, 1, "Jun là đơn vị ch", "Năng lượng", "Công suất ", "Nhiệt độ", "Gia tốc", 1, ""), 
(1, 1, "Đối với sự phát quang của vật, bước sóng của ánh sáng phát ra sẽ như thế nào so với ánh sáng chiếu tớ", "lớn hơn", "nhỏ hơn ", "bằng", "không xác định", 1, ""), 
(1, 1, "Theo thuyết tương đối hẹp của Einstein, vận tốc lớn nhất trong vũ trụ là vẫn tốc củ", "Ánh sáng", "Âm thanh", "Hố đen vũ trụ", "Bụi vũ trụ", 1, ""), 
(1, 1, "Đâu không phải thành phần của một nguyên t", "Proton", "Electron", "Photon", "Notron", 3, ""), 
(1, 1, "Hạt nào của nguyên tử không mang điê", "Proton", "Notron", "Electron", "Không hạt nào cả", 2, ""), 
(1, 1, "Tính chất nào sau đây không phải của lase", "Tính định hướng cao", "Độ đơn sắc cao", "Công suất lớn", "Cường độ lớn ", 3, ""), 
(1, 1, "Trong công thức lực đẩy Acsimet F=d.V, d là", "Khối lượng riêng của vật", "Khối lượng riêng của chất lỏng(khí)", "Trọng lượng riêng của vật", "Trọng lượng riêng của chất lỏng(khí)", 4, ""), 
(1, 1, "Marie Curie đã được nhận bao nhiêu giải Nobe", "1", "2", "3", "4", 2, ""), 
(1, 1, "Đâu không phải là sáng tác của nhạc sĩ Hoàng Việt", "Lá xanh", "Lá đỏ", "Nhạc rừng", "Tình ca (1957)", 2, ""), 
(1, 1, "Bộ phim tình cảm lãng mạn Titanic tham gia dự giải Orcar năm nào", "1995", "1997", "1999", "2001", 2, ""), 
(1, 1, "Diễn viên võ thuật Thành Long là ngôi sao người nước nào", "Trung Quốc đại lục", "Hồng Kông", "Đài Loan", "Mỹ", 2, ""), 
(1, 1, "Bộ phim hoạt hình đầu tiên của điện ảnh Cách mạng Việt Nam", "Chiếc vòng bạc", "Chú thỏ đi học", "Đáng đời thằng cáo", "Tấm cám", 3, ""), 
(1, 1, "Bộ phim nào sau đây được sản xuất sau năm 1975", "Chị Tư Hậu", "Nổi gió", "Em bé Hà Nội", "Ván bài lật ngửa", 4, ""), 
(1, 1, "Alexandre de Rhodes đã tổng hợp, định chế chữ quốc ngữ qua cuốn tự điển nào", "Việt - Bồ - La", "Việt - Pháp - La", "Việt - Ý - La", "Việt - Đức - La", 1, ""), 
(1, 1, "Người nào sau đây không phải là thành viên của Tự Lực văn đoàn", "Nhất Linh", "Thạch Lam", "Tú Mỡ", "Tú Xương", 4, ""), 
(1, 1, "Ai là tác giả của bức tranh Thiếu nữ bên hoa huệ", "Bùi Xuân Phái", "Tô Ngọc Vân", "Nguyễn Gia Trí", "Trần Văn Cẩn", 2, ""), 
(1, 1, "Ai là tác giả của tác phẩm Tam Quốc Diễn Nghĩa ", "La Quán Trung", "Thi Nại Am", "Ngô Thừa Ân", "Tào Tuyết Cần", 1, ""), 
(1, 1, "Ngô Thừa Ân là tác giả của tác phẩm nào sau đây", "Tây Du Kí", "Tam Quốc Diễn Nghĩa", "Hồng Lâu Mộng", "Thủy Hử", 1, ""), 
(1, 1, "Từ \"Thủy Hử\" trong tác phẩm cùng tên có nghĩa là gì", "Quán rượu", "Bến nước", "Quán nước", "Anh hùng ca", 2, ""), 
(1, 1, "Truyện Tam Quốc diễn nghĩa lấy bối cảnh cuối triều đại nào của Trung Quốc", "Hán", "Đường", "Tống", "Tần", 1, ""), 
(1, 1, "Lãnh tụ của các thủ lĩnh Lương Sơn Bạc trong truyện Thủy Hử", "Tống Giang", "Lỗ Trí Thâm", "Lâm Xung", "Võ Tòng", 1, ""), 
(1, 1, "Đâu không phải là một sáng tác của Lỗ Tấn", "Thuốc", "AQ chính truyện", "Nhật ký người điên", "Số phận con người", 4, ""), 
(1, 1, "Hai tác phẩm hài kịch Lão hà tiện và Trưởng giả học làm sang là của tác giả nào", "Victor Hugo", "Alexandre Dumas (cha)", "Môlie (Molière)", "Louis Aragon", 3, ""), 
(1, 1, "Nói đến thủ đô âm nhạc của châu Âu là ta nói đến thành phố nào", "Paris", "Viên", "Munich", "Roma", 2, ""), 
(1, 1, "Tác phẩm nào sau đây là văn học Anh", "Đồi gió hú", "Miếng da lừa", "Tiếng gọi nơi hoang dã", "Đông ki sốt", 1, ""), 
(1, 1, "Nhà văn Mark Twain là người nước nào", "Anh", "Mỹ", "Pháp", "Canada", 2, ""), 
(1, 1, "Theo kinh thánh,chúa trời đã sáng tạo ra vũ trụ và muôn loài trong mấy ngày", "5 ngày", "6 ngày", "10 ngày", "14 ngày", 2, ""), 
(1, 1, "Đạo Hồi tôn thờ ai", "Phật", "Thánh Allah", "Nhà tiên tri Muhammad", "Thiên thần Jibrael", 2, ""), 
(1, 1, "Thánh địa Mecca, nơi hành hương của các tín đồ đạo Hồi nằm ở quốc gia nào", "Palestin", "Các tiểu vương quốc Ả rập thống nhất", "Ả Rập Saudi", "Lebanon", 3, ""), 
(1, 1, "Đạo Phật được bắt nguồn từ quốc gia nào", "Ấn Độ", "Palestin", "Trung Quốc", "Thái Lan", 1, ""), 
(1, 1, "Ai được coi là người sáng lập ra Phật giáo", "Phật Thíchca Mâuni", "Phật Di Lặc", "Phật Ca Diếp", "Phật A di dà", 1, ""), 
(1, 1, "Tiếng Phạn là ngôn ngữ cổ của quốc gia nào", "Ấn Độ", "Trung Quốc", "Lào", "Campuchia", 1, ""), 
(1, 1, "Phố cổ Hội An là một đô thị cổ nằm bên bờ sông nào", "Thu Bồn", "Trà Khúc", "Sông Hàn", "Sông Nhật Lệ", 1, ""), 
(1, 1, "Tỉnh lị (trung tâm hành chính) của tỉnh Ninh Thuận là ở đâu", "TP Phan Rang Tháp Chàm", "TP Phan Thiết", "TP Hội An", "TP Nha Trang", 1, ""), 
(1, 1, "Biển Hồ, hạt ngọc của Pleiku có tên gọi là gì", "Hồ T'Nưng", "Hồ Ta Lư", "Hồ Sêrepok", "Hồ Tây Nguyên", 1, ""), 
(1, 1, "Hiện nay, lực lượng nào đảm nhiệm chức năng quốc phòng ở khu vực Tây Nguyên", "Quân khu 3", "Quân khu 4", "Quân khu 5", "Quân khu 6", 3, ""), 
(1, 1, "Công trình thủy điện Yaly được xây dựng ở tỉnh nào", "Gia Lai", "Cần Thơ", "Đồng Nai", "Đà Nẵng", 1, ""), 
(1, 1, "Tỉnh lỵ của tỉnh Đăk Lăk là Tp nào", "Buôn Mê Thuột", "Pleiku", "Đà Lạt", "Phan Thiết", 1, ""), 
(1, 1, "Địa danh Hồ Than Thở thuộc tp nào", "Đà Lạt", "Huế", "Pleiku", "Buôn Ma Thuột", 1, ""), 
(1, 1, "Theo kết quả điều tra dân sô 2009, vùng nào có tốc độ tăng dân số cao nhất cả nước", "Tây Nguyên", "Đồng bằng SCL", "Bắc Trung Bộ", "Đông Nam Bộ", 4, ""), 
(1, 1, "Thành phố Sài Gòn được đổi tên thành Thành phố Hồ Chí Minh năm nào", "1975", "1976", "1978", "1980", 2, ""), 
(1, 1, "Trunng tâm hành chính của tỉnh Bình Dương là ", "Thị xã Thủ Dầu Một", "Thị xã Thuận An", "Thị xã Dĩ An", "Thị xã Dầu Tiếng", 1, ""), 
(1, 1, "Núi Bà Đen thuộc tỉnh nào ở Đông Nam Bộ", "Đồng Nai", "Tây Ninh", "Bình Dương", "Bình Phước", 2, ""), 
(1, 1, "Quốc lộ 1A xuất phát (km0)  từ tỉnh nào ở nước ta", "Lạng Sơn", "Cao Bằng", "Lào Cai", "Quảng Ninh", 1, ""), 
(1, 1, "Loài cây biểu tượng của tỉnh Bến Tre", "Cây tre", "Cây dừa", "Cây lúa ", "Cây vải", 2, ""), 
(1, 1, "Thị xã Cao Lãnh là thuộc tỉnh nào", "Đồng Tháp", "An Giang", "Tiền Giang", "Bạc Liêu", 1, ""), 
(1, 1, "Có bao nhiêu nước thuộc khu vực Đông Nam Á", "9", "11", "13", "14", 2, ""), 
(1, 1, "Hiệp hội các quốc gia Đông Nam Á ASEAN được thành lập năm nào", "1967", "1965", "1969", "1970", 1, ""), 
(1, 1, "Khu vực Mậu dịch Tự do ASEAN được viết tắt là ", "AFTA", "NAFTA", "ATFA", "NATFA", 1, ""), 
(1, 1, "Việt Nam tham gia ASEAN năm bao nhiêu", "1993", "1995", "1997", "2000", 2, ""), 
(1, 1, "Đỉnh núi Kinabalu, nóc nhà của Đông Nam Á nằm ở quốc gia nào", "Malaysia", "Indonesia", "Singapore", "Brunei", 1, ""), 
(1, 1, "Ngôi sao ca nhạc Ronan Keating từng là thành viên của ban nhạc nổi tiếng nào", "Westlife", "Boyzone", "Backstreet Boys", "Micheal Learn to Rock", 2, ""), 
(1, 1, "Johann Sebastian Bach là nhà soạn nhạc cổ điển người nước nào", "Đức", "Pháp", "Anh", "Ý", 1, ""), 
(1, 1, "Nhạc sĩ Chopin là người nước nào", "Áo", "Ba Lan", "Thụy Sỹ", "Tây Ban Nha", 2, ""), 
(1, 1, "Bài hát Như có Bác trong ngày vui đại thắng là của nhạc sĩ nào", "Lưu Hữu Phước", "Phạm Tuyên", "Phan Huỳnh Điểu", "Hoàng Hiệp", 2, ""), 
(1, 1, "Chủ tịch đầu tiên của Hội Nhạc sĩ Việt Nam", "Nguyễn Xuân Khoát", "Văn Cao", "Trịnh Công Sơn", "Phạm Duy", 1, ""), 
(1, 1, "Bản giao hưởng đầu tiên của Việt Nam có tên là gì", "Quê hương", "Ngày hội", "Rhapsody Việt Nam", "Trăm sông đổ về biển Đông", 1, ""), 
(1, 1, "Ai là vị vua cuối cùng của triều đại nhà Lý", "Lý Chiêu Hoàng", "Lý Huệ Tông", "Lý Cao Tông", "Lý Thần Tông", 1, ""), 
(1, 1, "Đền Đô (Đền Lý Bát Đế ) là ở tỉnh nào", "Bắc Ninh", "Bắc Giang", "Bắc Kạn", "Hưng Yên", 1, ""), 
(1, 1, "Vị vua nào sau đây không được thờ trong đền Lý Bát Đế ", "Lý Thái Tổ", "Lý Thánh Tông", "Lý Chiêu Hoàng", "Lý Huệ Tông", 3, ""), 
(1, 1, "Nữ hoàng duy nhất trong lịch sử Việt Nam sống trong triều đại nào", "Lý", "Trần", "Nguyễn", "Hậu Lê", 1, ""), 
(1, 1, "Chùa Diên Hựu còn là tên gọi khác của ngôi chùa nào ở Hà Nội", "Chùa Một Cột", "Chùa Trần Quốc", "Chùa Quán Sứ", "Chùa Tứ Liên", 1, ""), 
(1, 1, "Chùa Một Cột được xây vào triều đại nào", "Trần", "Lý", "Tiền Lê", "Hậu Lê", 2, ""), 
(1, 1, "Trận đánh có ý nghĩa quyết định của cuộc chiến tranh chống quân xâm lược Tống lần II diễn ra trên sông nào ", "Bạch Đằng", "Như Nguyệt", "Sông Hồng", "Sông Đà", 2, ""), 
(1, 1, "Rượu Sâm panh phần lớn có màu gì", "Đỏ", "Xanh", "Trắng", "Đen", 1, ""), 
(1, 1, "Bộ phim nào đã giành được giải thưởng cho hạng mục phim hay nhất trong lễ trao giải Oscar lần thứ 84 năm 2012", "The Artist", "Hugo", "War Horse", "The Tree of Life", 1, ""), 
(1, 1, "Nữ diễn viên Meryl Streep đã giành được giải nữ diễn viên xuất sắc nhất trong lễ trao giải Oscar lần thứ 84 với bộ phim nào", "The Iron Lady", "The Help", "My Week with Marilyn", "The Artist", 1, ""), 
(1, 1, "Bộ phim The Artist, bộ phim chiến thắng trong hạng mục phim hay nhất trong lễ trao giải Oscar lần thứ 84 là của nền điện ảnh nào", "Pháp", "Mỹ", "Anh", "Canada", 1, ""), 
(1, 1, "Điệu hát nào sau đây không phải là một trong những di sản văn hóa phi vật thể của nước ta được UNESCO công nhận", "Chèo tàu", "Quan họ", "Hát xoan", "Ca trù", 1, ""), 
(1, 1, "Ai là tác giả bài thơ \"Nhớ rừng\"", "Thế Lữ", "Nhất Linh", "Thạch Lam", "Huy Cận", 1, ""), 
(1, 1, "Màu nào là màu chủ đạo trên lá cờ của tổ chức UNICEF, quỹ nhi đồng Liên Hợp Quốc", "Xanh", "Đỏ", "Tím", "Vàng", 1, ""), 
(1, 1, "Sau chiến thắng vào cuộc bầu cử tổng thống năm 2012, tổng thống Putin đã lần thứ mấy được bầu làm tổng thống Nga", "1", "2", "3", "4", 3, ""),

(1, 1, "Diện tích vùng biển Việt Nam gấp bao nhiêu lần diện tích đất liền Việt Nam", "Khoảng 2 lần", "Khoảng 3 lần ", "Khoảng 4 lần", "Khoảng 5 lần", 2, ""), 
(1, 1, "Sông Hồng đoạn qua Phú Thọ được gọi là sông gì", "Sông Cái", "Sông Nhị Hà", "Sông Nhĩ Hà", "Sông Thao", 4, ""), 
(1, 1, "Dân tộc nào có dân số đông thứ hai ở Việt Nam (sau người Kinh )", "Tày", "Mường", "Mông ", "Thái", 1, ""), 
(1, 1, "Tỉnh Lạng Sơn của Việt Nam giáp với tỉnh nào của Trung Quốc", "Vân Nam", "Quảng Đông", "Quảng Tây", "Hồng Kông", 3, ""), 
(1, 1, "Tỉnh Quảng Ninh có bao nhiêu thành phố trực thuộc tỉnh", "1 TP", "2 TP", "3 TP", "4 TP", 3, ""), 
(1, 1, "Cửa biển Nam Triệu nơi mà con sông Bạch Đằng đổ ra biển Đông nằm ở tỉnh, thành nào", "Hải Phòng", "Quảng Ninh", "Nam Định", "Thái Bình", 1, ""), 
(1, 1, "Hướng chính của sông Lam là hướng như thế nào", "Tây Bắc -Đông Nam", "Đông Bắc - Tây Nam", "Tây Nam - Đông Bắc", "Đông Nam - Tây Bắc", 1, ""), 
(1, 1, "Vườn quốc gia Phong Nha Kẻ Bàng được UNESCO công nhận là di sản thiên nhiên thế giới năm nào", "2001", "2002", "1999", "2003", 4, ""), 
(1, 1, "Vườn Quốc Gia Cát Tiên thuộc vùng nào của nước ta", "Tây Nam Bộ", "Đông Nam Bộ", "Tây Nguyên", "Nam Trung Bộ", 2, ""), 
(1, 1, "Thủ đô của nước Phần Lan", "Hensiki", "Copenhagen", "Ốtawa", "Stochom", 1, ""), 
(1, 1, "Hãy cho biết thủ đô của Austraylia", "Menbơn", "Canbơra", "Sydney", "Một thành phố khác", 2, ""), 
(1, 1, "Đèo Hải Vân là địa danh thuộc tỉnh thành nào ", "Đà Nẵng", "Khánh Hòa ", "Quảng Nam", "Bình Thuận", 1, ""), 
(1, 1, "Hầm đường bộ dài nhất Đông Nam Á nằm ở nước nào", "Thái Lan", "Indonesia", "Lào", "Việt Nam", 4, ""), 
(1, 1, "Địa danh Múi Né thuộc tỉnh nào", "Bình Thuận", "Ninh Thuận", "Phú Yên", "Khánh Hòa", 1, ""), 
(1, 1, "Địa danh nào sau đây không thuộc tỉnh Khánh Hòa", "Vịnh Nha Trang", "Tháp Bà", "Hòn Tre- Vilpearl Land", "Mũi Điện", 4, ""), 
(1, 1, "Tỉnh nào ở Tây Nguyên không có đường biên giới quốc tế", "Lâm Đồng", "Đắk Lắk", "Kon Tum", "Gia Lai", 1, ""), 
(1, 1, "Cồng Chiêng Tây Nguyên được UNESCO công nhận là Kiệt tác truyền khẩu và phi vật thể của nhân loại năm bao nhiêu", "2003", "2004", "2005", "2006", 3, ""), 
(1, 1, "Theo tiếng M'Nông, tên tỉnh Đăk Lắk có nghĩa là gì", "Hồ nước", "Biển hồ", "Thung lũng", "Cao nguyên", 1, ""), 
(1, 1, "Tỉnh nào dưới đây có 3 thị xã", "Bình Dương", "Bình Thuận", "Gia Lai", "Tây Ninh", 1, ""), 
(1, 1, "Tỉnh nào sau đây được tách ra từ tỉnh Sông Bé năm 1997", "Bình Dương và Bình Phước", "Tiền Giang và Hậu Giang", "An Giang và Kiên GIang", "Cần Thơ và Vĩnh Long", 1, ""), 
(1, 1, "Cây cầu dây văng có nhịp chính dài nhất Đông Nam Á là cầu nào , tính đến năm 2010", "Cầu Bãi Cháy ", "Cầu Cần Thơ", "Cầu Mỹ Thuận", "Cầu Bính", 2, ""), 
(1, 1, "Đường chí tuyến là vĩ tuyến nào", "23 độ 26 phút", "26 độ 23 phút", "22 độ 63 phút", "63 độ 22 phút", 1, ""), 
(1, 1, "Huyền thoại ca nhạc Elvis Presley được mệnh danh là ông vua của thể loại nhạc nào", "Pop", "Rock", "Dance", "Rock and Roll", 4, ""), 
(1, 1, "Ban nhạc The Beatles ra đời vào năm nào", "1950", "1960", "1970", "1980", 2, ""), 
(1, 1, "Ban nhạc The Beatles của nước Anh được thành lập tại thành phố nào", "Manchester", "London", "Liverpool", "Leeds", 3, ""), 
(1, 1, "Giải thưởng âm nhạc Grammy thường diễn ra vào tháng mấy trong năm", "Tháng 12", "Tháng 9", "Tháng 2", "Tháng 3", 3, ""), 
(1, 1, "Bài hát Chiến đấu vì độc lập tự do với câu mở đầu là Tiếng súng đã vang trên bầu trời biên giới là của nhạc sĩ nào", "Phạm Tuyên", "Lưu Hữu Phước", "Huy Du", "Hoàng Vân", 1, ""), 
(1, 1, "Nhạc sĩ Việt Nam viết opera với vở Cô Sao", "Đỗ Nhuận", "Hoàng Việt ", "Hoàng Hiệp", "Văn Cao", 1, ""), 
(1, 1, "Đâu không phải là một sáng tác cảu nhạc sĩ Đỗ Nhuận", "Việt Nam quê hương tôi", "Du kích sông Thao", "Nguyễn Trãi - Phi Khanh", "Mùa lúa chín", 4, ""), 
(1, 1, "Giải thưởng Sư tử vàng là của liên hoan phim nào trao tặng", "LHP Cannes", "LHP Berlin", "LHP Venezia", "LHP Pusan", 3, ""), 
(1, 1, "Bộ phim Dòng máu anh hùng - The Rebel  (2007) do hãng Cinema Pictures hợp tác với hãng phim nào sản xuất? ", "Chánh Phương", "Á Châu", "HK Phim", "Việt Phim", 1, ""), 
(1, 1, "Bộ phim nào là bộ phim truyện đầu tiên của điện ảnh Cách mạng Việt Nam", "Chung một dòng sông", "Chị Tư Hậu", "Chim vành khuyên", "Vợ chồng A Phủ", 1, ""), 
(1, 1, "Tác phẩm Nhà thờ Đức bà Paris là của nhà văn nào", "Victor Hugo", "Alexandre Dumas(cha)", "Alexandre Dumas (con)", "Balzac", 1, ""), 
(1, 1, "Tác phẩm nào sau đây không do Alexandre Dumas (cha) sáng tác", "Ba chàng lính ngự lâm", "Hoa Tulip đen", "Bá tước Monte Cristo", "Trà hoa nữ", 4, ""), 
(1, 1, "Tác phẩm Hồng Lâu Mộng lấy bối cảnh triều đại phong kiến nào của Trung Quốc", "Hán ", "Tần ", "Minh ", "Thanh", 4, ""), 
(1, 1, "Sunni và Shiite là hai dòng phái khác nhau của tôn giáo nào", "Hồi giáo", "Thiên chúa giáo", "Do Thái giáo", "Ấn Độ giáo", 1, ""), 
(1, 1, "Vị Phật được tôn thờ nhiều nhất trong Phật giáo Đại thừa", "Phật Thicshca Mâuni", "Phật Adiđà", "Phật Di Lặc", "Phật Ca Diếp", 2, ""), 
(1, 1, "Theo đạo Phật, Bồ Tát nào lắng nghe được mọi tiếng trên thế gian", "Quan Thế Âm ", "Địa Tạng", "Đại Thế Chí", "Hư Không Tạng", 1, ""), 
(1, 1, "Làng tranh dân gian Đông Hồ có con sông nào chảy qua", "Sông Luộc", "Sông Đuống", "Sông Cầu", "Sông Lục Nam", 2, ""), 
(1, 1, "Thành phố nào sau đây không thuộc Canada", "Toronto", "Vancouver", "Ottawa", "Venice", 4, ""), 
(1, 1, "Việt Nam là thành viên chính thức thứ bao nhiêu của tổ chức thương mại thế giới WTO", "130", "120", "140", "150", 4, ""), 
(1, 1, "Việt Nam chính thức trở thành thành viên của WTO năm nào", "2005", "2001", "2007", "2006", 3, ""), 
(1, 1, "Việt Nam lần đầu tiên đăng cai diễn đàn hợp tác kinh thế Thái Bình Dương năm nào", "2001", "2000", "2007", "2006", 4, ""), 
(1, 1, "Tính đến hết năm 2011, quốc gia nào là thành viên mới nhất của Liên Hợp Quốc", "Nam Sudan", "Đông Timo", "Serbia", "Palestine", 1, ""), 
(1, 1, "Liên Hợp Quốc được thành lập năm nào", "1941", "1945", "1946", "1948", 2, ""), 
(1, 1, "Tổ chức Liên Hợp Quốc được thành lập tại bang nào của Hoa Kỳ", "New York", "Washington DC", "California", "Massachusett", 3, ""), 
(1, 1, "Chữ cái E trong tên gọi của UNICEF - Quỹ nhi đồng Liên Hợp Quốc có nghĩa là gì", "Emergency", "Earn", "Ease", "Endangered", 1, ""), 
(1, 1, "Tia nào có bước sóng ngắn nhất trong các tia dưới đâ", "Tia X", "Tia tử ngoại", "Tia hồng ngoại", "Tia sáng màu đỏ", 1, ""), 
(1, 1, "Tia Rontgen còn được gọi l", "Tia X", "Tia hồng ngoại", "Tia tử ngoại", "Tia sáng mặt trời", 1, ""), 
(1, 1, "Nguyên tử khối của nguyên tố Chì ( Pb", "107", "109", "207", "209", 3, ""), 
(1, 1, "Đồng thau là hợp kim của hai kim loại nà", "Đồng và Sắt", "Đồng và Kẽm", "Đồng và Nhôm", "Đồng và Chì", 2, ""), 
(1, 1, "Kim loại nào cứng nhấ", "Vàng", "Bạc", "Crom", "Kim cương", 3, ""), 
(1, 1, "Kim loại nào nhẹ nhấ", "Đồng", "Nhôm", "Liti", "Natri", 3, ""), 
(1, 1, "Nước cường toan bao gồm tỉ lệ HCl : HNO3 là bao nhiê", "3:1", "3:2", "2:1", "2:3", 1, ""), 
(1, 1, "Nguyên tố chiếm tỉ lệ nhiều nhất trong vỏ trái đấ", "Heli", "Hidro", "Oxi", "Cácbon", 3, ""), 
(1, 1, "Hệ điều hành UNIX được viết trên ngôn ngữ lập trình nà", "C", "Pascal", "Basic", "Một ngôn ngữ khác", 1, ""), 
(1, 1, "Hệ điều hành Microsoft Windows 7 được phát hành vào năm nà", "2007", "2008", "2009", "2010", 3, ""), 
(1, 1, "Hệ điều hành nào được Microsoft ra mắt năm 200", "Windows XP", "Windows Vista", "Windows 7", "Windows 8", 2, ""), 
(1, 1, "Hãng Google của Hoa Kỳ được thành lập vào năm bao nhiê", "1994", "1996", "1998", "2000", 3, ""), 
(1, 1, "Chữ A trong hệ hexa (hệ 16 ) biểu diễn số nào trong hệ thập phâ", "10", "11", "12", "09", 1, ""), 
(1, 1, "hình thức hiện đại đầu tiên của thuyết nhật tâm do ai nêu r", "Nicolaus Copernicus", "Galileo Galilei", "Einstein", "Newton", 1, ""), 
(1, 1, "Anbert Einstein được giải Nobel vật lý nhờ công trình nghiên cứu ở lĩnh vực nà", "Quang điện", "Thuyết tương đối", "Hạt nhân", "Sóng ánh sáng", 1, ""), 
(1, 1, "0 độ C sẽ đổi được thành", "12 độ F", "22 độ F", "32 độ F", "42 độ F", 3, ""), 
(1, 1, "Động cơ nhiệt hoạt động theo chu trình Carnot phải trải qua mấy bướ", "1", "2", "3", "4", 4, ""), 
(1, 1, "Tỉnh thành nào ở nước ta có nhiều di sản được UNESCO công nhận nhất", "Quảng Nam", "Huế", "Quảng Ninh", "Hà Nội", 4, ""), 
(1, 1, "Viện bảo tàng Louvre là một trong những viện bảo tàng thu hút nhất trên thế giới. Viện bảo tàng này nằm ở đâu", "Anh", "Pháp", "Mỹ", "Hà Lan", 2, ""), 
(1, 1, "Dhaka là thủ đô của quốc gia Nam Á nào", "Pakistan", "Ấn Độ", "Butan", "Nêpan", 1, ""), 
(1, 1, "Giải thưởng nhại theo giải Nobel được trao hàng năm cho các công trình đáng chế nhạo gọi là gì", "Ig Nobel", "Hg Nobel", "Cg Nobel", "Kg Nobel", 1, ""), 
(1, 1, "Trong các vị thần của Thần thoại La Mã, đâu là Thần mặt trăng", "Jupiter", "Aurora", "Caelus", "Luna", 4, ""), 
(1, 1, "Tượng thần Vệ Nữ là một bức tượng Hy lạp cổ đại được phát hiện trên đảo nào", "Milos", "Enbơ", "Manta", "Venus", 1, ""), 
(1, 1, "Thời  Xuân Thu của Trung Quốc xảy ra cuối triều đại nào", "Hạ", "Thương", "Chu", "Tần", 3, ""), 
(1, 1, "Thủ đô của nhà Tần đặt tại Hàm Dương thuộc tỉnh nào của Trung Quốc hiện nay", "Thiểm Tây", "Quảng Đông", "Bắc Kinh", "Sơn Đông", 1, ""), 
(1, 1, "Lý Uyên là tên của vị vua đầu tiên của triều đại nào ở Trung Quốc", "Hán ", "Đường", "Tống", "Minh", 2, ""), 
(1, 1, "Chu Nguyên Chương là vị vua của triều đại nào ở Trung Quốc", "Minh", "Thanh", "Đường", "Tống", 1, ""), 
(1, 1, "Tử Cấm Thành của Trung Quốc được xây dựng dưới triều đại nào", "Thanh", "Đường", "Nguyên", "Minh", 4, ""), 
(1, 1, "Vị vua cuối cùng của triều đại phong kiến Trung Quốc", "Quang Tự", "Đạo Quang", "Đồng Trị", "Phổ Nghi", 4, ""), 
(1, 1, "Tổng thống lâm thời đầu tiên của Trung Hoa dân quốc", "Tưởng Giới Thạch", "Tôn Trung Sơn", "Viên Thế Khải", "Chu Ân Lai", 2, ""), 
(1, 1, "Chiến tranh thế giới thứ nhất được mở đầu vào năm nào", "1914", "1915", "1916", "1917", 1, ""), 
(1, 1, "Cách mạng Pháp 1789 đã lật đổ vua nào ", "Louis XVIII", "Louis  XVII", "Louis XVI", "Charles X", 3, ""), 
(1, 1, "Màu nào sau đây không có trong quốc kỳ của Cộng Hòa Pháp", "Đỏ", "Trắng", "Xanh lam", "Xanh lục", 4, ""), 
(1, 1, "Bức tường Berlin tại Đức bị phá bỏ vào năm nào", "1988", "1989", "1990", "1991", 2, ""), 
(1, 1, "Chiến dịch bão táp sa mạc là chiến dịch do Mỹ phát động để chiến tranh với nước nào ở vùng Trung Đông", "Iraq", "Afganishtan", "Sirya", "Lebanon", 1, ""), 
(1, 1, "Tổng thống nào của Mỹ đã bị buộc phải từ chức khi dính vào vụ Watergate ", "Nixon", "Johnson", "Gerald Ford", "Truman", 1, ""), 
(1, 1, "Trước khi làm tổng thống Mý, ông Barack Obama đã làm thượng nghĩ sĩ của bang nào", "Illinois", "New Jersey", "New York", "Texas", 1, ""), 
(1, 1, "Tổng thống Hoa Kỳ nào sau đây không thuộc Đảng Dân Chủ?", "Barack Obama", "Bill Clinton", "John Kennedy", "George W. Bush( con)", 4, ""), 
(1, 1, "Môn võ Vovinam từ xưa đến nay nổi tiếng với 3 đòn đánh. Đòn nào dưới đây không thuộc 3 đòn đánh đó", "Chỏ", "Chém quét", "Đòn chân kẹp cổ", "Khóa", 4, ""), 
(1, 1, "Kì thủ nào của người trẻ nhất đạt danh hiệu đại kiện tướng quốc tế", "Nguyễn Ngọc Trường Sơn", "Lê Quang Liêm", "Đào Thiên Hải", "Phạm Minh Hoàng", 1, ""), 
(1, 1, "Ai là tác giả của bài hát \" Hà Nội ngày trở về\" ", "NS Trần Tiến", "NS Phú Quang", "NS Hồng Đăng", "NS Trọng Đài", 2, ""), 
(1, 1, "Tên của môn thể thao \"Marathon\" là tên của ", "Một binh sĩ", "Một vị tướng", "Một cánh đồng", "Một thành phố", 3, ""), 
(1, 1, "Đại hội thể thao Olympic hiện đại đầu tiên được tổ chức vào năm nào", "1890", "1910", "1896", "1996", 3, ""), 
(1, 1, "Thế vân hội 1996 được tổ chức tại thành phố nào của nước Mỹ", "Atlanta", "New York", "Chicago", "Los Angeles", 1, ""), 
(1, 1, "Ủy ban Olympic quốc tế được viết tắt như thế nào", "OIC", "ICO", "CIO", "IOC", 4, ""), 
(1, 1, "Thế vận hội mùa đông 2010 được tổ chức tại thành phố Vancouver thuộc quốc gia nào", "Canada", "Ý", "Mỹ", "Úc", 1, ""), 
(1, 1, "Môn thể thao nào sau đây không có trong danh sách các môn thể thao tại Thế vận hội Bắc Kinh 2008", "Bóng chày", "Khúc gôn cầu trên cỏ", "Thuyền buồm", "Wushu", 4, ""), 
(1, 1, "SEA Games 25 được tổ chức tại quốc gia nào", "Lào", "Campuchia", "Myanmar", "Việt Nam", 1, ""), 
(1, 1, "Cầu thủ nào là người duy nhất giành được 3 World Cup dưới cương vị một cầu thủ", "Pelé", "Maradona", "Romario", "Franz Beckenbauer", 1, ""), 
(1, 1, "Bài hát \"Mùa hè Italia\" là bài hát chính thức của kỳ World Cup nào", "1986", "1990", "1998", "1982", 2, ""), 
(1, 1, "Cầu thủ nào sau đây là người ghi nhiều bàn thắng nhất các kỳ World cup ", "Ronaldo (Brasil)", "Gerd Müller (Đức)", "Miroslav Klose (Đức)", "Just Fontaine (Pháp)", 1, ""), 
(1, 1, "Quốc gia nào sau đây chưa từng đăng cai một kỳ World cup nào", "Thụy Điển", "Thụy Sĩ", "Argentina", "Bồ Đào Nha", 4, ""), 
(1, 1, "Quốc gia nào đã đăng cai World Cup 1994", "Mỹ", "Argentina", "Mexico", "Tây Ban Nha", 1, ""), 
(1, 1, "Mexico đã hai lần đăng cai giải vô địch bóng đá thế giới. Đó là năm 1970 và năm nào", "1982", "1986", "1990", "1994", 2, ""), 
(1, 1, "Đội tuyển quốc gia Uruguay đã mấy lần vô địch giải vô địch bóng đá thế giới World cup", "Chưa lần nào", "Một lần", "Hai lần", "Ba lần", 3, ""), 
(1, 1, "Cầu thủ nào đã ghi bàn thắng quyết định trong trận chung kết World cup 2010 giữa Tây Ban Nha và Hà Lan", "Xavi", "Alonso", "Iniesta", "Cesc Fàbregas", 3, ""), 
(1, 1, "Trận chung kết World cup 2006 tại Đức gồm có ĐT Ý và ĐT nào", "Anh", "Argentina", "Đức", "Pháp", 4, ""), 
(1, 1, "Cầu thủ nào là cầu thủ xuất sắc nhất World cup 2010 tại Nam Phi", "Robben - Hà Lan", "Iniesta - Tây Ban Nha", "Iker Casillas - Tây Ban Nha", "Diego Forlán - Uruguay", 4, ""), 
(1, 1, "Linh vật chính thức của World cup 2010 tại Nam Phi là con vật gì", "Chuột", "Mèo", "Báo hoa", "Lợn", 3, ""), 
(1, 1, "Đội tuyển nào đã vô địch giải vô địch bóng đá châu Âu được tổ chức lần đầu tiên", "Liên Xô", "Nam Tư", "Tây Ban Nha", "Đức", 1, ""), 
(1, 1, "Đội tuyển nào có số lần vô địch UEFA Champions Leauge nhiều nhất ( tính đến năm 2012)", "Real Madrid", "Barcelona", "Manchester United", "AC Milan", 1, ""), 
(1, 1, "Đội bóng nước Anh Manchester United đã giành được bao nhiêu chức vô địch cúp C1 Châu Âu", "1", "2", "3", "4", 3, ""), 
(1, 1, "Đội bóng nào là đội bóng Anh đầu tiên vô địch cúp C1 Châu Âu", "Manchester United", "Liverpool", "Chelsea", "Aston Villa", 1, ""), 
(1, 1, "Chiếc cúp nào sau đây không có trong cú ăn ba lịch sử của CLB Manchester United 1998-1999", "Cúp C1", "Cúp FA", "Cúp Ngoại hạng Anh", "Cúp vô địch thế giới các CLB", 4, ""), 
(1, 1, "Câu lạc bộ nào được LĐBĐ Thế giới FIFA bình chọn là CLB xuất sắc nhất thế giới thế kỷ 20", "Real Madrid", "Barcelona", "Liverpool", "Manchester United", 1, ""), 
(1, 1, "Vua nào của nhà Nguyễn đã đặt quốc hiệu nước ta là Việt Nam", "Gia Long", "Minh Mạng", "Thiệu Trị", "Tự Đức", 1, ""), 
(1, 1, "Vị vua nào sau đây đã đổi quốc hiệu nước ta thành Đại Nam", "Minh Mạng", "Gia Long", "Đồng Khánh", "Thiệu Trị", 1, ""), 
(1, 1, "Cuộc khởi nghĩa của Mai Thúc Loan là để chống lại sự đô hộ của triều đại nào", "Hán ", "Đường", "Lương", "Tùy", 2, ""), 
(1, 1, "Khổng Tử sinh ra tại nước nào thuộc nhà Chu", "Lỗ", "Triệu", "Ngụy", "Tần", 1, ""), 
(1, 1, "Ngô Quyền khi xưng vương đóng đô ở đâu", "Cổ Loa", "Đại La", "Hoa Lư", "Phong Châu", 1, ""), 
(1, 1, "Sau khi dẹp loạn 12 sứ quân, Đinh Bộ Lĩnh đã lên ngôi năm nào", "968", "978", "988", "998", 1, ""), 
(1, 1, "Câu thơ sau đây đã nhắc đến vị vua nào \" Bé thì chăn nghé chăn trâu - Trận bày đã lấy bông lau lầm cờ\"", "Đinh Bộ Lĩnh", "Quang Trung", "Ngô Quyền", "Mai Hắc Đế", 1, ""), 
(1, 1, "Triều Tiền Lê có tất cả bao nhiêu đời vua", "1", "2", "3", "4", 3, ""), 
(1, 1, "Vua Lê Đại Hành đã nói thác với sứ thần Trung Quốc rằng bị ngã ngựa đau chân để tránh phải làm gì", "Sang sứ nước Tống", "Ra đón sứ Tống", "Quỳ để nhận phong chức", "Tiễn sứ Tống về nước", 3, ""), 
(1, 1, "Cuộc chiến tranh chống quân Tống xâm lược của vua Lê Hoàn diễn ra vào năm nào", "881", "981", "1081", "1181", 2, ""), 
(1, 1, "Chữ \"Cồ\" trong quốc hiệu \"Đại Cồ Việt\" có nghĩa là gì", "Lớn", "Thái bình", "Phía nam", "Độc lập", 1, ""), 
(1, 1, "Vị vua nào đã cho xây dựng Văn Miếu", "Lý Thánh Tông", "Lý Thái Tổ", "Trần Thái Tông", "Lê Thánh Tông", 1, ""), 
(1, 1, "Khuê Văn Các tại Quốc Tử Giám được xây dựng vào thời nào", "Hậu Lê", "Lý ", "Trần", "Nguyễn", 4, ""), 
(1, 1, "Trước ý đồ xâm lược rõ ràng của nhầ Tống, quan quân nhà Lý dưới sự chỉ đạo của Lý Thường Kiệt đã làm gì trước tiên", "Tường cao hào sâu cố thủ", "Sang hòa hoãn với địch", "Sang đất Tống đánh đòn phủ đầu", "Đầu hàng vô điều kiện", 3, ""), 
(1, 1, "Tướng nào là chỉ huy của quân Tống xâm lăng Đại Việt lần II của nhà Tống", "Quách Quỳ", "Ô Mã Nhi", "Tô Giám", "Liễu Thăng", 1, ""), 
(1, 1, "Đất nước nào là quê hương của rượu Sâm panh", "Pháp", "Đức", "Anh", "Tây Ban Nha", 1, ""), 
(1, 1, "Màu nào sau đây không có trên quốc kỳ của Liên bang Nga", "Xanh lam", "Trắng", "Đỏ", "Xanh Lục", 4, ""), 
(1, 1, "L’arc de triomphe de l’Étoile là tên trong tiếng Pháp của công trình nổi tiếng nào ở Pháp", "Tháp Eiffel", "Khải hoàn môn", "Nhà thờ Đức Bà", "Cung điện Hoàng gia", 2, ""), 
(1, 1, "Bài quốc ca Pháp La Marseillaise được sáng tác trong cuộc chiến tranh nào", "Áo Phổ - Pháp", "Anh - Pháp", "Nga - Pháp", "Hà Lan - Pháp", 1, ""),

(1, 1, "Ranh giới lãnh hải của Việt Nam là bao nhiêu hải lý", "6 hải lý", "10 hải lý", "12 hải lý", "15 hải lý", 3, ""), 
(1, 1, "Vùng đặc quyền kinh tế biển ở Việt Nam là bao nhiêu hải lý", "100", "200", "250", "300", 2, ""), 
(1, 1, "Sông Hồng bắt nguồn từ tỉnh nào của Trung Quốc", "Vân Nam", "Quảng Đông", "Quảng Tây", "Phúc Kiến", 1, ""), 
(1, 1, "Hồ Thác Bà thuộc tỉnh nào", "Bắc Kạn", "Thái Nguyên", "Tuyên Quang", "Yên Bái", 4, ""), 
(1, 1, "Bộ sử thi Đẻ đất đẻ nước là của dân tộc nào", "Tày ", "Mường", "Mông", "Nùng", 2, ""), 
(1, 1, "Viêm Đế là một từ để chỉ vị vua cổ đại nào của Trung Quốc", "Thần Nông", "Đế Nghiêu", "Đế Thuấn", "Hoàng Đế", 1, ""), 
(1, 1, "Điểm cực tây của Việt Nam nằm ở huyện nào của tỉnh Điện Biên", "Mường Nhé", "Mường Chà", "Điện Biên Đông", "Mường Lay", 1, ""), 
(1, 1, "Dòng sông Lam chảy ra biển Đông qua cửa biển nào", "Cửa Hội", "Cửa Việt", "Cửa Tùng", "Cửa Ba Lạt", 1, ""), 
(1, 1, "Nhà thơ Hàn Mặc Tử và nhà thơ Lưu Trọng Lư cùng quê ở tỉnh nào", "Huế", "Quảng Bình", "Quảng Nam", "Nghệ An", 2, ""), 
(1, 1, "Chùa Thiên Mụ (Huế ) được xây dụng dưới thời chúa Nguyễn nào", "Nguyễn Hoàng", "Nguyễn Phúc Nguyên", "Nguyễn Phúc Lan", "Nguyễn Phúc Tần", 1, ""), 
(1, 1, "Tỉnh nào không thuộc vùng duyên hải Nam Trung Bộ (Theo từ điển Bách Khoa toàn thư Việt Nam)", "Bình Thuận", "Ninh Thuận", "Phú Yên", "Tây Ninh", 4, ""), 
(1, 1, "Địa danh nào sau đây không thuộc thành phố Đà Nẵng", "Bà Nà - Núi Chúa", "Đèo Hải Vân", "Ngũ Hành Sơn", "Thác bảy tầng ", 4, ""), 
(1, 1, "Thành phố nào của Việt Nam là thành phố kết nghĩa với thành phố Đà Nẵng", "Hà Nội", "Sài Gòn", "Hải Phòng", "Cần Thơ", 3, ""), 
(1, 1, "Hầm đường bộ Đèo Hải Vân nối liền hai tỉnh thành nào ở miền trung Việt Nam", "Huế- Đà Nẵng", "Đà Nẵng- Quảng Nam", "Huế- Quảng Nam", "Quảng Nam - Quảng Ngãi", 1, ""), 
(1, 1, "Hãy cho biết tỉnh lị của tỉnh Quảng Nam", "TP Tam Kỳ", "TP Hội An", "TP Đông Hà", "TP Phan Thiết", 1, ""), 
(1, 1, "Nhà máy lọc dầu Dung Quất được đặt tại tỉnh nào của Việt Nam", "Quảng Ngãi", "Ninh Thuận", "Bình Thuận", "Phú Yên", 1, ""), 
(1, 1, "Thuật ngữ \"Núi Ấn sông Trà \" dùng để chỉ tỉnh nào ở miền Trung Việt Nam? ", "Quảng Nam", "Quảng Ngãi", "Quảng Bình", "Quảng Trị", 2, ""), 
(1, 1, "Phố cổ Hội An được UNESCO công nhận là di sản văn hóa thế giới vào năm nào", "1994", "1999", "2000", "2003", 2, ""), 
(1, 1, "Tỉnh Phú Yên không giáp với tỉnh nào sau đây", "Đăk Lăk", "Gia Lai", "Bình Định", "Bình Thuận", 4, ""), 
(1, 1, "Khu vực Tây Nguyên gồm bao nhiêu tỉnh", "4", "5", "6", "7", 2, ""), 
(1, 1, "Biển số xe của tỉnh Bà Rịa - Vũng Tàu có 2 chữ số đầu là bao nhiêu", "70", "71", "72", "69", 3, ""), 
(1, 1, "Quê hương của anh hùng Võ Thị Sáu là ở tỉnh nào", "Tiền Giang", "Hậu Giang", "Bà Rịa - Vũng Tàu", "Đông Nai", 3, ""), 
(1, 1, "Việt Nam là thành viên thứ mấy gia nhập ASEAN", "thứ 6", "thứ 7", "thứ 2", "thứ 8", 2, ""), 
(1, 1, "Ca sĩ Robbie William từng là thành viên của ban nhạc nào", "Boyzone", "Take That", "Micheal Learn to Rock", "The Beatles", 2, ""), 
(1, 1, "Hàm lượng Các bon trong Thép là khoảng bao nhiêu phần trăm", "0 - 1", "0 - 1.5", "0- 0.5", "0- 2", 4, ""), 
(1, 1, "Kim loại có nhiều nhất trong vỏ trái đất", "Sắt", "Nhôm", "Đồng", "Bạc", 2, ""), 
(1, 1, "Nguyên tố nào có giá đắt nhất", "Urani", "Vàng", "Bạch Kim", "Californi", 4, ""), 
(1, 1, "Hồng ngọc có cấu tạo như thế nào", "Nguyên tố Rubi", "Oxit nhôm có crom", "Oxit sắt liên kết với Rubi", "Oxit Crom có Sắt", 2, ""), 
(1, 1, "Hạt nào sau đây không phải là hạt bền", "Proton", "Neutron", "Electron", "Nơtrino", 2, ""), 
(1, 1, "Tia alpha gồm những hạt anpha sẽ bị lệch về", "Cực âm của điện trường", "Cực âm của từ trường", "Cực dương của điện trường", "Cực dương của từ trường", 1, ""), 
(1, 1, "Hạt alpha được cấu tạo bởi các hạt nào", "3 neutron và 3proton", "2 proton và 2 neutron", "3 neutron và 2 proton", "3 proton và 2 neutron", 2, ""), 
(1, 1, "Hạt nào không phải là sản phẩm của phân rã beta", "Neutron", "Electron", "electron antineutrino", "Proton", 1, ""), 
(1, 1, "Phiên bản Linux đầu tiên được viết bởi người nước nào", "Mỹ", "Thụy Điển", "Phần Lan", "Thụy Sỹ", 3, ""), 
(1, 1, "Hệ điều hành Microsoft Windows được ra mắt đầu tiên vào năm nào", "1980", "1985", "1990", "1995", 2, ""), 
(1, 1, "Trụ sở của Apple đặt tại bang nào", "New York", "Washington", "Illinois", "California", 4, ""), 
(1, 1, "Thung lũng Silicon đặt tại bang nào", "California", "New York", "New Jersey", "Hawaii", 1, ""), 
(1, 1, "Công ty nào sau đây không nằm trong thung lũng Silicon, Hoa Kỳ", "Electronic Art", "Google", "Apple", "Microsoft", 4, ""), 
(1, 1, "Tên niêm yết trên thị trường NASDAG của Microsoft", "MICS", "MICR", "MSFT", "MSOF", 3, ""), 
(1, 1, "Trường đại học có trụ sở tại thung lũng Silicon Hoa Kỳ ", "Stanford", "California", "Havard", "MIT", 1, ""), 
(1, 1, "Nhiệt độ không tuyệt đối là trạng thái nhiệt động học lý tưởng của vật chất, trong đó mọi chuyển động nhiệt đều ngừng. Hãy cho biết độ không tuyệt đối có nhiệt độ là bao nhiêu", "-100 độ C", "-175 độ C", "-173 độ C", "-273 độ C", 4, ""), 
(1, 1, "Chất nào sau đây có năng suất tỏa nhiệt lớn nhất", "Than", "Hidro", "Metan", "Êtan", 4, ""), 
(1, 1, "Vật liệu nào sau đây dẫn điện tốt nhất", "Bạc ", "Vàng", "Nhôm ", "Sắt", 1, ""), 
(1, 1, "Hạt Proton được cấu tạo bởi những hạt quắc nào", "u-u-d", "u-s-d", "u-d-d", "s-u-u", 1, ""), 
(1, 1, "Trong lĩnh vực âm nhạc, khi một nghệ sĩ hay ban nhạc bán được 1 đĩa bạch kim tức là họ bán được bao nhiêu đĩa", "1 triệu", "20 triệu", "100 triệu", "50 triệu", 1, ""), 
(1, 1, "Nhạc sĩ Mozart sống ở thế kỷ nào", "17", "16", "18", "19", 3, ""), 
(1, 1, "Bài ca chính thức của Liên Minh Châu Âu được lấy từ chương thứ tư của bản giao hưởng số mấy của Beethoven", "Giao hưởng số 5", "Giao hưởng số 6", "Giao hưởng số 7", "Giao hưởng số 9", 4, ""), 
(1, 1, "Liên hoan phim lâu đời nhất thế giới", "LHP Moscow", "LHP Venezia", "LHP Berlin", "LHP Cannes", 2, ""), 
(1, 1, "Bộ phim nào sau đây không nằm trong nhóm những bộ phim được trao nhiều giải Orcar nhất mọi thời đại ( 11 giải)", "Titanic", "Sự trở lại của nhà vua", "Ben - Hur", "Cuốn theo chiều gió", 4, ""), 
(1, 1, "Phim Triệu phú khu ổ chuột được trao 8 giải Orcar nhưng không giành được giải nào sau đây", "Phim xuất sắc nhất", "Đạo diễn xuất sắc nhất", "Kịch bản chuyển thể hay nhất", "Nam diễn viên chính xuất sắc nhất", 4, ""), 
(1, 1, "Nội dung của bộ phim Cuốn theo chiều gió dựa trên bối cảnh nước Mỹ đang trong hoàn cảnh nào", "Nội chiến Mỹ và thời kì tái thiết", "Thế chiến thứ nhất", "Thế chiến thứ hai", "Giữa hai cuộc chiến tranh thế giới", 1, ""), 
(1, 1, "Thông thường liên hoan phim Việt Nam được tổ chức mấy năm một lần", "Hai năm", "Ba năm ", "Bốn năm", "Năm năm", 1, ""), 
(1, 1, "Vua hề Sác Lô (Charles Spencer Chaplin) là diễn viên, đạo di���n phim hài người nước nào", "Anh", "Pháp ", "Đức", "Tây Ban Nha", 1, ""), 
(1, 1, "Vai chính Dịu trong phim Vĩ tuyên 17 ngày và đêm của đạo diễn Hải Ninh do ai thể hiện", "Trà Giang", "Lan Hương", "Thu An", "Thụy Vân", 1, ""), 
(1, 1, "Đạo diễn bộ phim Vĩ tuyến 17 ngày và đêm (1972 )", "Huy Thành", "Hải Ninh", "Trần Vũ", "Hồng Sến", 2, ""), 
(1, 1, "Diễn viên nào sau đây không tham gia bộ phim Em bé Hà Nội của đạo diễn Hải Ninh", "Trà Giang", "Thế Anh", "Lan Hương", "Thụy Vân", 4, ""), 
(1, 1, "Phim nào sau đây không có sự góp mặt của diễn viên NSND Trà Giang", "Chị Tư Hậu", "Vĩ tuyến 17 ngày và đêm", "Em bé Hà Nội", "Người chiến sĩ trẻ", 4, ""), 
(1, 1, "Tác phẩm nào được coi là cuốn tiểu thuyết hiện đại đầu tiên của Việt Nam", "Thầy Lazarô Phiền", "Tố Tâm", "Hồn bướm mơ tiên", "Gánh hàng hoa", 1, ""), 
(1, 1, "Trong các nhân vật sau đây, nhân vật nào không có trong các tác phẩm của Victor Hugo", "Nàng Côdet", "Thanh tra Giave", "Thằng gù Quasimodo", "Chàng Raphaël de Valentin ", 4, ""), 
(1, 1, "Nhân vật chính trong tiểu thuyết Không gia đình của Hector Malot là ai", "Chú bé Rêmi", "Chú bé Matchia", "Bà Milligan", "Vitalis", 1, ""), 
(1, 1, "Chiến tranh và hòa bình là bộ tiểu thuyết nói về cuộc chiến tranh nào", "Thế chiến I", "Thế chiến II", "Chiến trang Nga- Nhật", "Chiến tranh Nga - Pháp", 4, ""), 
(1, 1, "Cuộc chiến tranh giữa Israel và các nước Ả Rập lấng giềng năm 1967 được gọi là", "Chiến tranh sáu ngày", "Chiến tranh năm ngày", "Chiến tranh mười ngày", "Chiến tranh bốn ngày", 1, ""), 
(1, 1, "Từ \" Hồi giáo\" hay \"Islam\" trong tiếng Ả Rập có nghĩa là gì", "Vâng mệnh thượng đế", "Kinh Koran", "Ăn chay", "Đấng tối cao duy nhất", 1, ""), 
(1, 1, "Người Hồi giáo hàng năm phải thực hiện tháng ăn chay để", "Tưởng nhớ và thương xót người nghèo", "Giảm chi phí cuộc sống", "Không sát sinh", "Tâm hồn trong sạch", 1, ""), 
(1, 1, "Tại sao người Hồi giáo không được ăn thịt con lợn", "Vì không muốn sát sinh", "Vì thịt lợn đắt", "Vì lợn là con vật bẩn thỉu", "Vì lợn được coi là một vị thần linh", 3, ""), 
(1, 1, "Đẳng cấp cao nhất trong xã hội Ấn Độ thời xưa thuộc hạng người nào", "Bà-la-môn", "Sát-đế-ly", "Vệ-xa", "Thu-Đà-La", 1, ""), 
(1, 1, "Giáo hoàng Bênêđictô XVI (trị vì từ năm 2005 ) là người nước nào", "Đức", "Anh ", "Pháp", "Ý", 1, ""), 
(1, 1, "Dòng tranh Thủy Mặc của Trung Quốc có nguồn gốc xuất phát từ tôn giáo nào", "Đạo giáo", "Phật Giáo", "Nho Giáo", "Mặc Giáo", 1, ""), 
(1, 1, "Tổ chức Y tế thế giới WHO có trụ sở tại thành phố nào", "New York", "Geneva", "Bắc Kinh", "Tokyo", 2, ""), 
(1, 1, "Chữ M trong tên của Quỹ tiền tệ quốc tế IMF có nghĩa là gì", "Money", "Monetary", "Main", "Mother", 2, ""), 
(1, 1, "Hồ Victoria là hồ nước ngọt lớn thứ hai trên thế giới về diện tích bề mặt. Hồ này nằm ở châu lục nào", "Châu Á", "Châu Mỹ", "Châu Phi", "Châu Âu", 3, ""), 
(1, 1, "Hồ sâu nhất thế giới nằm ở quốc gia nào", "Mỹ", "Canada", "Ai Cập", "Nga", 4, ""), 
(1, 1, "Lĩnh vực nào không nằm trong lĩnh vực trao giải của giải thưởng Nobel", "Vật lý", "Hóa học", "Toán học", "Y học", 3, ""), 
(1, 1, "Giải thưởng Nobel Hòa bình được trao hàng năm ở quốc gia nào", "Nauy", "Thụy Điển", "Phần Lan", "Đan Mạch", 1, ""), 
(1, 1, "Trong tiếng Nhật, từ \"kami\" mà tạo lên từ \"origami\" nghĩa là gì", "Gấp", "Cắt", "Giấy", "Bìa", 3, ""), 
(1, 1, "Hades, Pluto , Osiris đều là các vị thần nào trong các câu chuyện thần thoại", "Thần mặt trời", "Thần biển cả ", "Thần mặt trăng", "Thần diêm vương", 4, ""), 
(1, 1, "Thần Apollo trong thần thoại Hy Lạp là vị thần nào", "Thần ánh sáng", "Thần biển cả", "Thần nông", "Thần mặt trời", 1, ""), 
(1, 1, "Người đẹp Ngô Phương Lan, hoa hậu Thế giới người Việt 2007 với tư cách hoa hậu đến từ", "Nhật Bản", "Các quốc gia SNG", "Mỹ", "Thụy Sỹ", 4, ""), 
(1, 1, "Sự kiện nào mở đầu cuộc chiến tranh thế giới lần thứ nhất ", "Hoàng tử Áo - Hung bị ám sát", "Hoàng đế Đức xua quân đánh Pháp, Bỉ", "Đức tấn công Pháp tại Verdun", "Anh - Pháp đánh Đức tại sông Somme", 1, ""), 
(1, 1, "Nước nào là nước có diện tích lớn nhất trong Liên minh Châu Âu", "Anh", "Pháp", "Tây Ban Nha", "Nga", 2, ""), 
(1, 1, "Vương triều 100 ngày của Napoléon đã bị sụp đổ sau thất bại nào", "Trận Waterloo", "Trận Austerlitz", "Trận Moskva", "Trận Ai Cập", 1, ""), 
(1, 1, "Pharaon, từ dùng để chỉ các vị vua Ai Cập cổ đại, có nghĩa là gì", "Ngôi nhà lớn", "Dòng sông lớn", "Cung điện lớn", "Vị vua vĩ đại", 1, ""), 
(1, 1, "Tổng thống nào của Hoa Kỳ đã phát động chiến tranh vùng vịnh chống lại Iraq", "George H. W. Bush (cha)", "George W. Bush (con)", "Ronald Reagan", "Bill Clinton", 1, ""), 
(1, 1, "Theo quy định quốc tế, các võ sĩ Judo từ 9 đẳng đến 10 đẳng thì mang đai màu gì", "Trắng", "Nâu", "Đỏ ", "Đen", 3, ""), 
(1, 1, "Võ phục Vovinam trên toàn thế giới dùng thống nhất màu nào hiện nay", "Đen", "Đỏ", "Xanh lam", "Tím", 3, ""), 
(1, 1, "Loại đai cao nhất của môn võ Vovinam là loại đai nào", "Hồng đai", "Hoàng đai", "Bạch đai", "Huyền đai", 3, ""), 
(1, 1, "Đối với môn võ Vovinam hiện nay, màu đai đỏ là biểu hiện của cái gì", "Máu", "Lửa", "Màu cờ tổ quốc", "Mặt trời", 2, ""), 
(1, 1, "Đại hội thể thao Đông Nam Á lần đầu tiên được tổ chức tại đâu", "Thái Lan", "Việt Nam", "Lào", "Miến Điện", 1, ""), 
(1, 1, "Chiếc cúp \"Nữ thần chiến thắng\" duy nhất được FIFA trao tặng cho Brasil sau lần thứ ba vô địch thế giới của họ vào năm nào", "1962", "1970", "1974", "1994", 2, ""), 
(1, 1, "Đội bóng nào về nhì tại World cup 1998 tại Pháp", "Pháp", "Italia", "Brasil", "Đức", 3, ""), 
(1, 1, "\"YOU'LL NEVER WALK ALONE\" là khẩu hiệu của đội bóng nào của nước Anh", "Manchester United", "Liverpool", "Chelsea", "Manchester City", 2, ""), 
(1, 1, "Trận chung kết Champions Leauge mùa giải 1998-1999 giữa Manchester United và Bayern Munich được đá trên sân nào", "Nou Camp", "Old Trafford", "Santiago Bernabéu", "San Siro", 1, ""), 
(1, 1, "Cầu thủ nào đã ghi bàn thắng quyết định trong trận chung kết cúp C1 châu Âu 1998-1999 giữa MU và Bayern Munich?", "Ole Gunnar Solskjær", "Teddy Sheringham ", "Paul Scholes", "David Beckham", 1, ""), 
(1, 1, "Vị vua nào đã đổi tên nước ta là Đại Việt", "Lý Thái Tổ", "Lý Thánh Tông", "Trần Thái Tông", "Trần Nhân Tông", 2, ""), 
(1, 1, "Hai câu thơ \"Hùng cứ châu Hoan đất một vùng - Vạn An thành lũy khói hương xông \" đã nhắc đến vị vua nào", "Lý Nam Đế ", "Triệu Việt Vương", "Mai Hắc Đế", "Ngô Quyền", 3, ""), 
(1, 1, "Trong thời kỳ loạn 12 sứ quân, lực lượng sứ quân nào đã hợp nhất với sứ quân Đinh Bộ Lĩnh", "Nguyễn Siêu", "Trần Lãm", "Ngô Nhật Khánh", "Kiều Công Hãn", 2, ""), 
(1, 1, "Vị vua nào còn được gọi là Vạn Thắng Vương", "Đinh Tiên Hoàng", "Ngô Quyền", "Lê Thái Tổ", "Lê Đại Hành", 1, ""), 
(1, 1, "Triều đại phong kiến nào là triều đại đầu tiên cho đúc tiền ở Việt Nam", "Lý", "Đinh", "Tr���n", "Tiền Lê", 2, ""), 
(1, 1, "Bài thơ Quốc tộ (Vận nước ) của thiền sư Pháp Thuận được viết vào thời nào", "Đinh", "Tiền Lê", "Trần", "Hậu Lê", 2, ""), 
(1, 1, "Quốc tử giám tại kinh thành Thăng Long được lập vào thời vua nào", "Lý Thánh Tông", "Lý Nhân Tông", "Trần Thái Tông", "Trần Anh Tông", 2, ""), 
(1, 1, "Chu Văn An đã dâng \"Thất trảm sớ\" xin chém bảy tên nịnh thần lên vua nào", "Trần Dụ Tông", "Trần Anh Tông", "Trần Thái Tông", "Trần Nhân Tông", 1, ""), 
(1, 1, "Chữ A thứ 2 trong tên  AMPAS - Viện hàn lâm Khoa học và Nghệ thuật Điện Ảnh Hoa Kỳ là viết tắt của từ gì", "Academy", "Art", "American", "America", 2, ""), 
(1, 1, "Quỹ nhi đồng Liên Hợp Quốc UNICEF được thành lập vào năm nào", "1945", "1946", "1954", "1960", 2, ""), 
(1, 1, "Tổng thống Nga (2012) Vladimir Putin sinh ra tại thành phố nào", "Moscow", "St. Petersburg", "Volgograd", "Mordovia", 2, ""),

(1, 1, "Phụ lưu lớn nhất của sông Hồng", "Sông Cầu", "Sông Đà", "Sông Lô", "Sông Thái Bình", 2, ""), 
(1, 1, "Sông Hồng có chiều dài khoản", "600 km", "800 km", "1000 km", "1200 km", 4, ""), 
(1, 1, "Đồng bằng sông Hồng gồm bao nhiêu tỉnh, thành ph", "10", "11", "12", "13", 1, ""), 
(1, 1, "Tên gọi \"Sa Pa\" trong tiếng Quan Thoại có nghĩa là gì", "Sương mù", "Bãi cát ", "Thung lũng", "Thác nước", 2, ""), 
(1, 1, "Nguồn gốc từ \"ĐÀ NẴNG\" là biến dạng của từ Chăm \"DAKNAN\". Từ \"NAN\" có nghĩa là gì", "Biển lớn", "Rộng, lớn", "Cát vàng", "Nắng lớn", 2, ""), 
(1, 1, "Người sáng lập ra nhóm Tự lực văn đoàn - Nhất Linh quê ở đâu", "Quảng Nam", "Đà Nẵng", "Quảng Bình", "Quảng Trị", 1, ""), 
(1, 1, "Tỉnh nào ở miền Trung Việt Nam được biết đến với tên gọi \"Quê mía xứ đường\" ", "Quảng Nam", "Quảng Ngãi", "Ninh Thuận", "Bình Thuận", 2, ""), 
(1, 1, "Trong ngôn ngữ Ba Na thì tên tỉnh Kontum nghĩa là gì", "Biển Hồ", "Làng Hồ", "Núi Hồ", "Rừng Hồ", 2, ""), 
(1, 1, "Theo tiếng địa phương tên đỉnh Fansipan có nghĩa là gì", "Phiến đá khổng lồ", "Đỉnh núi khổng lồ", "Đỉnh trời", "Cổng trời", 1, ""), 
(1, 1, "Ngôi sao nhạc Pop Micheal Jackson sinh năm bao nhiêu", "1958", "1954", "1962", "1964", 1, ""), 
(1, 1, "Ngôi sao ca nhạc người Mỹ Elvis Presly sinh tại bang nào của Mỹ", "Ohio", "New York", "Mississippi", "Michigan", 3, ""), 
(1, 1, "Đâu không phải là thành viên của ban nhạc The Beatles trong danh sách dưới đây", "Paul McCartney", "George Harrison", "Ringo Starr", "Mick Jagger", 4, ""), 
(1, 1, "Bản giao hưởng số 9 của nhạc sĩ Beethven có tên là gì", "Niềm vui", "Định mệnh", "Đồng quê", "Mùa xuân", 1, ""), 
(1, 1, "Đâu không phải là một trong những bút danh của nhạc sĩ Lưu Hữu Phước", "Huỳnh Minh Siêng", "Long Hưng", "Anh Lưu", "Anh Vũ", 4, ""), 
(1, 1, "Liên hoan phim Cannes được tổ chức lần đầu tiên vào năm nào", "1946", "1950", "1940", "1955", 1, ""), 
(1, 1, "Bộ phim truyện đầu tiên được thực hiện tại Việt Nam", "Kim Vân Kiều", "Đồng tiền kẽm tậu được con ngựa", "Tấn tôn đức Bảo Đại", "Cả Lố", 1, ""), 
(1, 1, "Bộ phim đầu tiên của diễn viên NSND Thế Anh là bộ phim nào", "Nổi gió", "Mối tình đầu", "Tự thú trước bình minh", "Đêm hội Long Trì", 1, ""), 
(1, 1, "Nhà thơ La Fontaine của Pháp sống vào thế kỷ thứ bao nhiêu", "16", "17", "19", "15", 2, ""), 
(1, 1, "Đâu không phải là một trong năm trụ cột của Hồi giáo", "SALAT Cầu nguyện", "ZAKAT Bố thí", "SAVVM Nhịn ăn", "HAJJ Đến nhà thờ", 4, ""), 
(1, 1, "Đâu không phải là một chân lý của Tứ diệu đế, cơ sở tư tưởng của Phật pháp", "Khổ đế", "Tập đế", "Diệt đế", "Cao đế", 4, ""), 
(1, 1, "Theo Tứ diệu đế của Phật gia, đường dẫn đến Niết- bàn là", "Bát chính đạo", "Cửu chính đạo", "Ngũ chính đạo", "Thập chính đạo", 1, ""), 
(1, 1, "Từ Niết-bàn  của Phật gia có nghĩa là gì?", "Thổi tắt", "An nhàn", "Thiền", "Cuộc sống mới", 1, ""), 
(1, 1, "Saturn là vị thần nào trong Thần thoại La Mã", "Thần nông", "Thần chết", "Thần đồng quê", "Thần chiến tranh", 1, ""), 
(1, 1, "Chàng thanh niên trẻ trong tượng David của Michelangelo là ai", "Một vị vua", "Người đánh cá", "Nông dân", "Thương gia", 1, ""), 
(1, 1, "Kim loại mẫn cảm với ánh sáng nhấ", "Cesi", "Natri", "Kali", "Liti", 1, ""), 
(1, 1, "Tia nào không phải là sản phẩm của phản ứng phân hạc", "alpha", "beta", "gamma", "X", 4, ""), 
(1, 1, "Khối lượng mặt trời gấp bao nhiêu lần khối lượng trái đấ", "300,000", "30,000", "40,000", "400,000", 1, ""), 
(1, 1, "Tỉnh thành phố nào ở Việt Nam có một nét văn hóa rất đặc biệt là thờ cá voi ( có 10 đền thờ cá voi)", "Long An", "Kiên Giang", "Cà Mau", "Bả Rịa - Vũng Tàu", 4, ""), 
(1, 1, "Vịnh nào sau đây không là thành viên của CLB những vịnh đẹp nhất thế giới", "Vịnh Hạ Long", "Vịnh Nha Trang", "Vịnh Lăng Cô", "Vịnh Cam Ranh", 4, ""), 
(1, 1, "Nóc nhà của thế giới, đỉnh Everest, trong tiếng Tây Tạng gọi là Chomolangma có nghĩa là gì", "Thánh mẫu vũ trụ", "Phật pháp vô biên", "Cõi niết bàn", "Trán trời", 1, ""), 
(1, 1, "Con sông nào còn được biết tới với cái tên là \" Thủy lộ vàng\"", "Hoàng Hà", "Trường Giang", "Tương Giang", "Hoài Giang", 2, ""), 
(1, 1, "Nguyệt Chi là từ trong tiếng Trung để chỉ người ở khu vực nào", "Đông Nam Á cổ đại", "Trung Á cổ đại", "Tây Á cổ đại", "Châu Âu cổ đại", 2, ""), 
(1, 1, "Hệ điều hành UNIX do công ty nào sản xuấ", "Microsoft", "AT&T Bell Labs", "Niklaus Wirth", "Sun Microsystems", 2, ""), 
(1, 1, "Trụ sở của hãng Microsoft đặt tại bang nà", "Washington", "New York", "Texas", "Ohio", 1, ""), 
(1, 1, "Microsoft thành lập vào năm bao nhiê", "1970", "1975", "1976", "1977", 2, ""), 
(1, 1, "Một hạt proton có khối lượng gấp khoảng bao nhiêu lần hạt electro", "1000", "2000", "3000", "4000", 2, ""), 
(1, 1, "3 hạt quắc u-d-d cấu tạo lên hạt nào dưới đâ", "electron", "proton", "notron", "phản proton", 3, ""), 
(1, 1, "Để phân biệt với tên nước Trung Hoa, người Trung Quốc cổ đại đã gọi các tộc lạc hậu ở phía bắc là gì", "Di", "Nhung", "Địch", "Man", 3, ""), 
(1, 1, "Hội Quốc Liên là tổ chức quốc tế ra đời sau Thế Chiến I được thành lập năm bao nhiêu", "1918", "1919", "1920", "1917", 2, ""), 
(1, 1, "Tổng bí thư Đảng Cộng Sản Liên Xô Gorvachev được trao giải Nobel hòa bình năm nào", "1988", "1989", "1990", "1991", 3, ""), 
(1, 1, "Chữ \"Ai\" trong tên môn võ thuật Aikido trong chữ Hán-Nhật (Kanji ) có nghĩa là gì", "Tinh thần", "Con đường", "Mềm dẻo", "Hài hòa", 4, ""), 
(1, 1, "Hai cầu thủ có số lần tham dự vòng chung kết World cup nhiều nhất là hai cầu thủ người Mexico và người nước nào", "Đức", "Brasil", "Pháp", "Tây Ban Nha", 1, ""), 
(1, 1, "HLV Alex Ferguson đã bắt đầu dẫn dắt CLB Manchester United ở mùa giải nào", "1985-1986", "1986-1987", "1987-1988", "1988-1989", 2, ""), 
(1, 1, "Nguyên nhân chính của việc vua Lê Đại Hành mang quân sang trừng phạt nước Chiêm Thành", "Không chịu sang sứ", "Không cống nạp vật phẩm", "Bắt giữ sứ giả", "Khiêu khích biên giới", 3, ""), 
(1, 1, "Sau cách mạng Pháp 1789, năm 1793, vua Louis XVI cùng hoàng hậu đã bị xử tử trên quảng trường nào", "Concorde", "Quinconces", "Bastille", "Italie", 1, "") 
;